# Generated by Django 6.0.8 on 2026-09-01 11:27

import app_spark_api.utils.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationNumber',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='conversation_number', serialize=False, to='projects.project', verbose_name='所属项目')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='已发放的最大序号')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', app_spark_api.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='会话 ID')),
                ('number', models.PositiveIntegerField(verbose_name='会话序号')),
                ('tenant_id', models.CharField(default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'indexes': [models.Index(fields=['project', '-created'], name='conversatio_project_266884_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'number'), name='uniq_conversation_number_per_project')],
            },
        ),
    ]
