# Generated by Django 6.0.8 on 2026-09-24 07:47

import app_spark_api.utils.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationNumber',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='conversation_number', serialize=False, to='projects.project', verbose_name='所属项目')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='已发放的最大序号')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', app_spark_api.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='会话 ID')),
                ('number', models.PositiveIntegerField(verbose_name='会话序号')),
                ('state_epoch', models.PositiveIntegerField(default=1, verbose_name='状态回写授权代次')),
                ('closed_at', models.DateTimeField(default=None, null=True, verbose_name='结束时间')),
                ('tenant_id', models.CharField(default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(max_length=64, verbose_name='产生该检查点的 run')),
                ('commit', models.CharField(max_length=64, verbose_name='仓库提交')),
                ('tag', models.CharField(max_length=255, verbose_name='钉住该提交的远端 tag')),
                ('context_version', models.PositiveIntegerField(verbose_name='配套的上下文版本')),
                ('completed', models.BooleanField(default=True, verbose_name='该 run 是否完整结束')),
                ('log_seq', models.PositiveIntegerField(default=0, verbose_name='原始记录游标')),
                ('ui_event_seq', models.PositiveIntegerField(default=0, verbose_name='AG-UI 事件游标')),
                ('state_epoch', models.PositiveIntegerField(default=1, verbose_name='写入时的状态回写代次')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='conversations.conversation', verbose_name='所属会话')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationContextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_version', models.PositiveIntegerField(verbose_name='上下文版本')),
                ('backend', models.CharField(max_length=32, verbose_name='存储引擎')),
                ('config', models.JSONField(default=dict, verbose_name='存储引擎配置')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_versions', to='conversations.conversation', verbose_name='所属会话')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='会话内序号')),
                ('run_id', models.CharField(max_length=64, verbose_name='产生这条记录的 run')),
                ('payload', models.JSONField(verbose_name='记录内容，原样透传')),
                ('recorded_at', models.DateTimeField(verbose_name='Runtime 侧记录该条目的时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='所属会话')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationUiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='会话内序号')),
                ('run_id', models.CharField(max_length=64, verbose_name='产生这条记录的 run')),
                ('payload', models.JSONField(verbose_name='记录内容，原样透传')),
                ('recorded_at', models.DateTimeField(verbose_name='Runtime 侧记录该条目的时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_events', to='conversations.conversation', verbose_name='所属会话')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationUserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', app_spark_api.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('run_id', models.CharField(default=None, max_length=64, null=True, verbose_name='接受该输入的 run')),
                ('content', models.TextField(verbose_name='用户输入原文')),
                ('after_seq', models.PositiveIntegerField(default=0, verbose_name='插入位置之前的 UI event 序号')),
                ('tenant_id', models.CharField(default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='conversations.conversation', verbose_name='所属会话')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['project', '-created_at'], name='conversatio_project_1ec45b_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='uniq_conversation_number_per_project'),
        ),
        migrations.AddIndex(
            model_name='conversationcheckpoint',
            index=models.Index(fields=['conversation', '-created_at'], name='conversatio_convers_1255c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationcheckpoint',
            constraint=models.UniqueConstraint(fields=('conversation', 'commit'), name='uniq_conversation_checkpoint_commit'),
        ),
        migrations.AddIndex(
            model_name='conversationcontextversion',
            index=models.Index(fields=['conversation', '-context_version'], name='conversatio_convers_affc48_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationcontextversion',
            constraint=models.UniqueConstraint(fields=('conversation', 'context_version'), name='uniq_conversation_context_version'),
        ),
        migrations.AddConstraint(
            model_name='conversationmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='uniq_conversationmessage_seq'),
        ),
        migrations.AddIndex(
            model_name='conversationuievent',
            index=models.Index(fields=['conversation', '-seq'], name='conv_ui_event_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationuievent',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='uniq_conversationuievent_seq'),
        ),
        migrations.AddIndex(
            model_name='conversationusermessage',
            index=models.Index(fields=['conversation', 'after_seq', 'id'], name='conversatio_convers_62fe8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationusermessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'run_id'), name='uniq_conversation_user_run'),
        ),
    ]
