# Generated by Django 6.0.8 on 2026-09-04 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationContextSnapshot',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='context_snapshot', serialize=False, to='conversations.conversation', verbose_name='所属会话')),
                ('context_version', models.PositiveIntegerField(default=0, verbose_name='上下文版本')),
                ('backend', models.CharField(max_length=32, verbose_name='存储引擎')),
                ('config', models.JSONField(default=dict, help_text='HostTmpPath 使用 {"path": "/var/lib/app-spark/contexts/<uuid>.json"}，BkRepo 使用 {"bucket": "app-spark", "key": "conversations/<uuid>/context.json"}', verbose_name='存储引擎配置')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='state_epoch',
            field=models.PositiveIntegerField(default=1, verbose_name='状态回写授权代次'),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='会话内序号')),
                ('run_id', models.CharField(max_length=64, verbose_name='产生这条记录的 run')),
                ('payload', models.JSONField(verbose_name='记录内容，原样透传')),
                ('recorded_at', models.DateTimeField(verbose_name='Runtime 侧记录该条目的时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='所属会话')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('conversation', 'seq'), name='uniq_conversationmessage_seq')],
            },
        ),
        migrations.CreateModel(
            name='ConversationUiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='会话内序号')),
                ('run_id', models.CharField(max_length=64, verbose_name='产生这条记录的 run')),
                ('payload', models.JSONField(verbose_name='记录内容，原样透传')),
                ('recorded_at', models.DateTimeField(verbose_name='Runtime 侧记录该条目的时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_events', to='conversations.conversation', verbose_name='所属会话')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('conversation', 'seq'), name='uniq_conversationuievent_seq')],
            },
        ),
    ]
