# Generated by Django 6.0.8 on 2026-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversationcontextsnapshot_conversation_state_epoch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='closed_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='结束时间'),
        ),
    ]
