# Generated by Django 6.0.8 on 2026-09-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(max_length=64, verbose_name='产生该检查点的 run')),
                ('commit', models.CharField(max_length=64, verbose_name='仓库提交')),
                ('tag', models.CharField(max_length=255, verbose_name='钉住该提交的远端 tag')),
                ('context_version', models.PositiveIntegerField(verbose_name='配套的上下文版本')),
                ('log_seq', models.PositiveIntegerField(default=0, verbose_name='原始记录游标')),
                ('ui_event_seq', models.PositiveIntegerField(default=0, verbose_name='AG-UI 事件游标')),
                ('state_epoch', models.PositiveIntegerField(default=1, verbose_name='写入时的状态回写代次')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='conversations.conversation', verbose_name='所属会话')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationContextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('context_version', models.PositiveIntegerField(verbose_name='上下文版本')),
                ('backend', models.CharField(max_length=32, verbose_name='存储引擎')),
                ('config', models.JSONField(default=dict, verbose_name='存储引擎配置')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_versions', to='conversations.conversation', verbose_name='所属会话')),
            ],
        ),
        migrations.DeleteModel(
            name='ConversationContextSnapshot',
        ),
        migrations.AddIndex(
            model_name='conversationcheckpoint',
            index=models.Index(fields=['conversation', '-created'], name='conversatio_convers_be0ee7_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationcheckpoint',
            constraint=models.UniqueConstraint(fields=('conversation', 'commit'), name='uniq_conversation_checkpoint_commit'),
        ),
        migrations.AddIndex(
            model_name='conversationcontextversion',
            index=models.Index(fields=['conversation', '-context_version'], name='conversatio_convers_affc48_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationcontextversion',
            constraint=models.UniqueConstraint(fields=('conversation', 'context_version'), name='uniq_conversation_context_version'),
        ),
    ]
