# Generated by Django 6.0.8 on 2026-09-17 09:48

import app_spark_api.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0004_conversationcheckpoint_conversationcontextversion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationUserMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("owner", app_spark_api.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ("run_id", models.CharField(default=None, max_length=64, null=True, verbose_name="接受该输入的 run")),
                ("content", models.TextField(verbose_name="用户输入原文")),
                ("after_seq", models.PositiveIntegerField(default=0, verbose_name="插入位置之前的 UI event 序号")),
                (
                    "tenant_id",
                    models.CharField(
                        default="default", help_text="本条数据的所属租户", max_length=32, verbose_name="租户 ID"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_messages",
                        to="conversations.conversation",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["conversation", "after_seq", "created", "id"], name="conversatio_convers_3b87a7_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("conversation", "run_id"), name="uniq_conversation_user_run")
                ],
            },
        ),
    ]
