# Generated by Django 6.0.8 on 2026-09-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0005_conversationusermessage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversationuievent",
            index=models.Index(fields=["conversation", "-seq"], name="conv_ui_event_latest_idx"),
        ),
    ]
