# Generated by Django 6.0.8 on 2026-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversationuievent_conv_ui_event_latest_idx'),
        ('projects', '0002_rename_created_project_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conversatio_project_266884_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversationcheckpoint',
            name='conversatio_convers_be0ee7_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversationusermessage',
            name='conversatio_convers_3b87a7_idx',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='conversationcheckpoint',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversationcheckpoint',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='conversationcontextversion',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversationcontextversion',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='conversationusermessage',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversationusermessage',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['project', '-created_at'], name='conversatio_project_1ec45b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcheckpoint',
            index=models.Index(fields=['conversation', '-created_at'], name='conversatio_convers_1255c7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationusermessage',
            index=models.Index(fields=['conversation', 'after_seq', 'created_at', 'id'], name='conversatio_convers_0fe2e0_idx'),
        ),
    ]
