# Generated by Django 6.0.8 on 2026-09-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_remove_conversation_conversatio_project_266884_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversationusermessage',
            name='conversatio_convers_0fe2e0_idx',
        ),
        migrations.AddIndex(
            model_name='conversationusermessage',
            index=models.Index(fields=['conversation', 'after_seq', 'id'], name='conversatio_convers_62fe8a_idx'),
        ),
    ]
