# Generated by Django 3.2.12 on 2023-12-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230717_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneOffCommand',
        ),
    ]
