# Generated by Django 4.2.16 on 2024-12-05 11:47

from django.db import migrations, models
import paas_wl.bk_app.applications.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_delete_oneoffcommand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="name",
            field=models.SlugField(
                max_length=64,
                unique=True,
                validators=[
                    paas_wl.bk_app.applications.models.validators.validate_app_name
                ],
            ),
        ),
    ]
