# Generated by Django 4.2.16 on 2024-12-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_app_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="app",
            unique_together=set(),
        ),
    ]
