# Generated by Django 4.2.17 on 2025-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_app_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AlterField(
            model_name="buildprocess",
            name="status",
            field=models.CharField(default="pending", max_length=12),
        ),
    ]
