# Generated by Django 4.2.16 on 2025-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_app_tenant_id_alter_buildprocess_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="buildprocess",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
