# Generated by Django 4.2.17 on 2025-04-23 06:45

from django.db import migrations
import paas_wl.bk_app.applications.entities
import paas_wl.bk_app.applications.models.build


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_build_tenant_id_buildprocess_tenant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="artifact_metadata",
            field=paas_wl.bk_app.applications.models.build.BuildArtifactMetadataField(
                default=paas_wl.bk_app.applications.entities.BuildArtifactMetadata,
                help_text="构件元信息, 包括 entrypoint/use_cnb/use_dockerfile/proc_entrypoints 等信息",
            ),
        ),
    ]
