# Generated by Django 4.2.17 on 2025-05-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_build_artifact_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="build",
            name="procfile",
        ),
    ]
