# Generated by Django 5.2.15 on 2026-08-12 08:11

import paas_wl.utils.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_config_tenant_id_outputstream_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='build',
            name='application_id',
            field=paas_wl.utils.models.Char32UUIDField(null=True, verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='build',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(null=True, verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='build',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='buildprocess',
            name='application_id',
            field=paas_wl.utils.models.Char32UUIDField(null=True, verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='buildprocess',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(null=True, verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='buildprocess',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='config',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='outputstream',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='release',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
