# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/paas.bk.tencent.com_bkapps.yaml
- bases/paas.bk.tencent.com_domaingroupmappings.yaml
- bases/paas.bk.tencent.com_projectconfigs.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# NOTE: conversion webhook work for convert k8s resource to another version，such as v1alpha1 -> v2beta2
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#customresourceconversion-v1-apiextensions-k8s-io
- path: patches/webhook_in_bkapps.yaml
#- path: patches/webhook_in_domaingroupmappings.yaml
#- path: patches/webhook_in_projectconfigs.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
# NOTE: ca inject here is only work for conversion webhook，not affect the working of the Validating & Mutating webhook
- path: patches/cainjection_in_bkapps.yaml
#- path: patches/cainjection_in_domaingroupmappings.yaml
#- path: patches/cainjection_in_projectconfigs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
