# Generated by Django 4.2.23 on 2025-08-21 03:33

from django.db import migrations, models
import paasng.utils.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBuildRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('source_origin', models.CharField(choices=[('package', '源码包'), ('repo', '代码仓库')], max_length=32, verbose_name='源码来源')),
                ('repository_address', models.CharField(blank=True, default='', help_text='源码仓库地址, 只有 source_origin 是 repo 时才有值', max_length=256)),
                ('repository_branch', models.CharField(blank=True, default='', help_text='源码仓库分支, 只有 source_origin 是 repo 时才有值', max_length=128)),
                ('package_name', models.CharField(blank=True, default='', help_text='源码包名, 只有 source_origin 是 package 时才有值', max_length=256)),
                ('signature', models.CharField(help_text='数字签名, 当 source_origin 是 package 时才有值', max_length=256)),
                ('artifact_url', models.TextField(blank=True, default='', help_text='s-mart 构建产物地址, 用于下载')),
                ('status', models.CharField(help_text='s-mart 构建任务成功与否', max_length=32)),
                ('build_int_requested_at', models.DateTimeField(help_text='用户请求中断 build 的时间', null=True)),
                ('time_spent', models.IntegerField(help_text='s-mart 构建任务整体花费的时间 (单位: 秒)', null=True)),
                ('operator', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
