# Generated by Django 6.0.8 on 2026-08-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSourceStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(help_text='源码存储引擎，例如 host_tmp_path 或 bk_repo', max_length=32)),
                ('config', models.JSONField(default=dict, help_text='存储引擎配置，例如 HostTmpPath 使用 {"path": "/tmp/project-source.tgz"}，BkRepo 使用 {"bucket": "project-source", "key": "projects/demo/source.tgz"}')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_storage', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
