# Generated by Django 6.0.8 on 2026-09-10 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectSourceStorage",
        ),
    ]
