# Generated by Django 3.2.12 on 2022-05-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_config_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMetricsMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('port', models.IntegerField(help_text='Service 端口')),
                ('target_port', models.IntegerField(help_text='容器内的端口')),
                ('is_enabled', models.BooleanField(help_text='是否启动 AppMetrics', default=True)),
                ('app', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.app')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
