# Generated by Django 4.2.30 on 2026-06-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paas_service', '0009_alter_plan_unique_together_plan_tenant_id_and_more'),
        ('monitoring', '0002_auto_20221026_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoExpandEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=64, verbose_name='仓库名称')),
                ('old_size', models.BigIntegerField(help_text='单位字节', verbose_name='扩容前配额')),
                ('new_size', models.BigIntegerField(help_text='单位字节', verbose_name='扩容后配额')),
                ('step_size', models.BigIntegerField(help_text='单位字节', verbose_name='扩容步长')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instance', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='paas_service.serviceinstance')),
            ],
        ),
    ]
