# Generated by Django 3.2.12 on 2023-05-15 09:45

from django.db import migrations, models
import paasng.engine.constants


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20220509_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='runtime_type',
            field=models.CharField(default=paasng.engine.constants.RuntimeType['BUILDPACK'], max_length=32, verbose_name='运行时类型'),
        ),
    ]
