# Generated by Django 3.2.12 on 2023-12-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_auto_20231218_1740'),
        ('modules', '0011_auto_20231019_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='appslugbuilder',
            name='step_meta_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='构建步骤集', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slugbuilders', to='engine.stepmetaset'),
        ),
    ]
