# Generated by Django 3.2.12 on 2024-04-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_buildconfig_use_bk_ci_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildconfig',
            name='image',
        ),
    ]
