# Generated by Django 3.2.25 on 2024-05-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_remove_buildconfig_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appslugbuilder',
            name='type',
            field=models.CharField(choices=[('legacy', 'cnb'), ('cnb', 'cnb')], default='legacy', max_length=32, verbose_name='镜像类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appslugrunner',
            name='type',
            field=models.CharField(choices=[('legacy', 'cnb'), ('cnb', 'cnb')], default='legacy', max_length=32, verbose_name='镜像类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appbuildpack',
            name='type',
            field=models.CharField(choices=[('tar', 'tar'), ('oci-embedded', 'oci-embedded'), ('oci-image', 'oci-image'), ('oci-file', 'oci-file')], max_length=32, verbose_name='引用类型'),
        ),
    ]
