# Generated by Django 3.2.25 on 2024-09-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_auto_20240511_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appslugbuilder',
            name='type',
            field=models.CharField(choices=[('legacy', 'legacy'), ('cnb', 'cnb')], max_length=32, verbose_name='镜像类型'),
        ),
        migrations.AlterField(
            model_name='appslugrunner',
            name='type',
            field=models.CharField(choices=[('legacy', 'legacy'), ('cnb', 'cnb')], max_length=32, verbose_name='镜像类型'),
        ),
    ]
