# Generated by Django 4.2.17 on 2025-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0016_auto_20240904_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
