# Generated by Django 4.2.17 on 2025-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_buildconfig_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbuildpack',
            name='type',
            field=models.CharField(choices=[('tar', 'tar'), ('tgz', 'tgz'), ('oci-embedded', 'oci-embedded'), ('oci-image', 'oci-image'), ('oci-file', 'oci-file')], max_length=32, verbose_name='引用类型'),
        ),
    ]
