# Generated by Django 4.2.17 on 2025-07-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0019_remove_appbuildpack_modules_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appslugbuilder",
            name="dev_sandbox_image",
            field=models.CharField(blank=True, max_length=256, verbose_name="开发沙箱镜像（含 Tag）"),
        ),
    ]
