# Generated by Django 4.2.30 on 2026-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0020_appslugbuilder_dev_sandbox_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="appbuildpack",
            name="stack",
            field=models.CharField(
                blank=True,
                default="",
                help_text="该 buildpack 适用的运行时栈标识，如 heroku-24；为空表示默认栈",
                max_length=64,
                verbose_name="运行时栈",
            ),
        ),
    ]
