# Generated by Django 5.2.15 on 2026-08-12 08:11

import paasng.utils.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0021_appbuildpack_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildconfig',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
