# Generated by Django 3.2.12 on 2022-07-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20220506_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayoptions',
            name='open_mode',
            field=models.CharField(choices=[('desktop', '桌面'), ('new_tab', '新标签页')], default='new_tab', max_length=20, verbose_name='打开方式'),
        ),
    ]
