# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except
in compliance with the License. You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing permissions and
limitations under the License.

We undertake not to change the open source license (MIT license) applicable
to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.12 on 2022-11-01 10:03

from django.db import migrations
import paasng.bk_plugins.pluginscenter.models.definitions
import paasng.bk_plugins.pluginscenter.models.instances


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0002_auto_20221025_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='sync_members',
            field=paasng.bk_plugins.pluginscenter.models.definitions.PluginBackendAPIResourceField(null=True),
        ),
        migrations.AlterField(
            model_name='pluginrelease',
            name='stages_shortcut',
            field=paasng.bk_plugins.pluginscenter.models.instances.StagesShortcutField(
                default=list, help_text='发布阶段简易索引(保证顺序可靠)', null=True
            ),
        ),
    ]
