# Generated by Django 3.2.12 on 2023-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0010_plugininstance_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationrecord',
            name='subject',
            field=models.CharField(choices=[('plugin', '插件'), ('version', '版本'), ('basic_info', '基本信息'), ('logo', 'logo'), ('market_info', '市场信息'), ('config_info', '配置信息'), ('visible_range', '可见范围')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pluginmarketinfo',
            name='category',
            field=models.CharField(db_index=True, max_length=64, verbose_name='分类'),
        ),
    ]
