# Generated by Django 3.2.12 on 2023-09-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0012_pluginreleasestage_pipeline_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginreleasestage',
            name='operator',
            field=models.CharField(max_length=32, null=True, verbose_name='操作人'),
        ),
    ]
