# Generated by Django 3.2.12 on 2023-11-23 03:14

from django.db import migrations
import paasng.bk_plugins.pluginscenter.models.definitions


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0013_pluginreleasestage_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='overview_page',
            field=paasng.bk_plugins.pluginscenter.models.definitions.PluginoverviewPageField(null=True),
        ),
    ]
