# Generated by Django 3.2.12 on 2023-11-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0014_pluginbasicinfodefinition_overview_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='extra_fields_order',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pluginmarketinfodefinition',
            name='extra_fields_order',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('add', '新建'), ('re-release', '重新发布'), ('terminate', '终止发布'), ('modify', '修改'), ('delete', '删除'), ('archive', '下架'), ('reactivate', '重新上架')], max_length=32),
        ),
    ]
