# Generated by Django 3.2.12 on 2023-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0015_auto_20231125_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='extra_fields_en',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pluginmarketinfodefinition',
            name='extra_fields_en',
            field=models.JSONField(default=dict),
        ),
    ]
