# Generated by Django 3.2.12 on 2024-01-30 06:50

from django.db import migrations, models
import django.db.models.deletion
import paasng.bk_plugins.pluginscenter.models.definitions


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0017_auto_20231204_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugindefinition',
            name='test_release_revision',
            field=paasng.bk_plugins.pluginscenter.models.definitions.ReleaseRevisionDefinitionField(null=True),
        ),
        migrations.AddField(
            model_name='plugindefinition',
            name='test_release_stages',
            field=paasng.bk_plugins.pluginscenter.models.definitions.ReleaseStageDefinitionField(null=True),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='subject',
            field=models.CharField(choices=[('plugin', '插件'), ('test_version', '测试版本'), ('version', '版本'), ('basic_info', '基本信息'), ('logo', 'logo'), ('market_info', '市场信息'), ('config_info', '配置信息'), ('visible_range', '可见范围')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pluginrelease',
            name='type',
            field=models.CharField(choices=[('prod', '正式发布'), ('test', '测试发布')], max_length=16, verbose_name='版本类型(正式/测试)'),
        ),
        migrations.CreateModel(
            name='PluginVisibleRangeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description_zh_cn', models.TextField(default='', verbose_name='description')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='description')),
                ('scope', models.JSONField(default=list)),
                ('pd', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='visible_range_definition', to='pluginscenter.plugindefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PluginVisibleRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bkci_project', models.JSONField(default=list, verbose_name='蓝盾项目ID')),
                ('organization', models.JSONField(blank=True, null=True, verbose_name='组织架构')),
                ('plugin', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='pluginscenter.plugininstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PluginReleaseStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(choices=[('gray', '灰度发布'), ('full', '全量发布')], max_length=32, verbose_name='发布策略')),
                ('bkci_project', models.JSONField(blank=True, null=True, verbose_name='蓝盾项目ID')),
                ('organization', models.JSONField(blank=True, null=True, verbose_name='组织架构')),
                ('release', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='release_strategy', to='pluginscenter.pluginrelease')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
