# Generated by Django 3.2.25 on 2024-05-15 07:46

from django.db import migrations, models
import paasng.bk_plugins.pluginscenter.constants


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0018_auto_20240130_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginreleasestage',
            name='status_polling_method',
            field=models.CharField(default=paasng.bk_plugins.pluginscenter.constants.StatusPollingMethod['API'], help_text='冗余字段, 用于减少查询次数', max_length=16, verbose_name='阶段的状态轮询方式'),
        ),
        migrations.AlterField(
            model_name='pluginreleasestrategy',
            name='bkci_project',
            field=models.JSONField(blank=True, help_text="格式：['1111', '222222']", null=True, verbose_name='蓝盾项目ID'),
        ),
    ]
