# Generated by Django 3.2.25 on 2024-05-17 07:44

from django.db import migrations, models
import paasng.bk_plugins.pluginscenter.constants
import paasng.bk_plugins.pluginscenter.models.definitions


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0019_auto_20240515_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='access_mode',
            field=models.CharField(default=paasng.bk_plugins.pluginscenter.constants.PluginBasicInfoAccessMode['READWRITE'], max_length=16, verbose_name='基本信息查看模式'),
        ),
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='description_zh_cn',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='publisher_description_en',
            field=models.TextField(blank=True, default='', verbose_name='publisher_description'),
        ),
        migrations.AddField(
            model_name='pluginbasicinfodefinition',
            name='publisher_description_zh_cn',
            field=models.TextField(default='', verbose_name='publisher_description'),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='publisher',
            field=models.CharField(default='', max_length=64, verbose_name='插件发布者'),
        ),
        migrations.AlterField(
            model_name='pluginmarketinfodefinition',
            name='category',
            field=paasng.bk_plugins.pluginscenter.models.definitions.PluginBackendAPIResourceField(null=True),
        ),
    ]
