# Generated by Django 3.2.25 on 2024-05-20 05:15

from django.db import migrations, models
import paasng.bk_plugins.pluginscenter.models.instances


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0020_auto_20240517_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginvisiblerange',
            name='is_in_approval',
            field=models.BooleanField(default=False, verbose_name='是否在审批中'),
        ),
        migrations.AddField(
            model_name='pluginvisiblerange',
            name='itsm_detail',
            field=paasng.bk_plugins.pluginscenter.models.instances.ItsmDetailField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='subject',
            field=models.CharField(choices=[('plugin', '插件'), ('test_version', '测试版本'), ('version', '版本'), ('basic_info', '基本信息'), ('logo', 'logo'), ('market_info', '市场信息'), ('config_info', '配置信息'), ('visible_range', '可见范围'), ('publisher', '发布者')], max_length=32),
        ),
    ]
