# Generated by Django 3.2.25 on 2024-07-30 09:52

from django.db import migrations, models
import django.db.models.deletion
import paasng.bk_plugins.pluginscenter.models.instances


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0021_auto_20240520_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginreleasestrategy',
            name='itsm_detail',
            field=paasng.bk_plugins.pluginscenter.models.instances.ItsmDetailField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pluginreleasestrategy',
            name='release',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='release_strategies', to='pluginscenter.pluginrelease'),
        ),
    ]
