# Generated by Django 3.2.25 on 2024-08-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0023_auto_20240812_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrelease',
            name='is_rolled_back',
            field=models.BooleanField(default=False, help_text='是否已回滚'),
        ),
        migrations.AlterField(
            model_name='pluginvisiblerange',
            name='plugin',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='visible_range', to='pluginscenter.plugininstance'),
        ),
    ]
