# Generated by Django 3.2.25 on 2024-08-27 08:24

from django.db import migrations, models
import paasng.bk_plugins.pluginscenter.constants


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0024_auto_20240814_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrelease',
            name='gray_status',
            field=models.CharField(default=paasng.bk_plugins.pluginscenter.constants.GrayReleaseStatus['IN_GRAY'], max_length=32, verbose_name='灰度发布状态'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('add', '新建'), ('re-release', '重新发布'), ('terminate', '终止发布'), ('modify', '修改'), ('delete', '删除'), ('archive', '下架'), ('reactivate', '重新上架'), ('rollback', '回滚')], max_length=32),
        ),
    ]
