# Generated by Django 4.2.16 on 2025-02-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pluginscenter", "0025_auto_20240827_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationrecord",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="plugininstance",
            name="app_tenant_id",
            field=models.CharField(
                default="",
                help_text="插件对哪个租户的用户可用，当租户模式为全租户时，本字段值为空",
                max_length=32,
                verbose_name="插件租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="plugininstance",
            name="app_tenant_mode",
            field=models.CharField(
                default="global",
                help_text="插件在租户层面的可用范围，可选值：全租户、指定租户",
                max_length=16,
                verbose_name="插件租户模式",
            ),
        ),
        migrations.AddField(
            model_name="plugininstance",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="pluginmarketinfo",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="pluginrelease",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="pluginreleasestage",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="pluginreleasestrategy",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="pluginvisiblerange",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
