# Generated by Django 4.2.17 on 2025-04-22 03:53

from django.db import migrations
import paasng.bk_plugins.pluginscenter.models.definitions


class Migration(migrations.Migration):

    dependencies = [
        (
            "pluginscenter",
            "0026_operationrecord_tenant_id_pluginconfig_tenant_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plugindefinition",
            name="options",
            field=paasng.bk_plugins.pluginscenter.models.definitions.PluginOptionsField(
                default=None, help_text="插件额外配置项", null=True
            ),
        ),
    ]
