# Generated by Django 4.2.17 on 2025-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pluginscenter",
            "0026_operationrecord_tenant_id_pluginconfig_tenant_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plugindefinition",
            name="add_admin_to_plugin_members",
            field=models.BooleanField(default=False),
        ),
    ]
