# Generated by Django 5.2.15 on 2026-09-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pluginscenter", "0028_alter_approvalservice_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginrelease",
            name="release_process",
            field=models.CharField(
                choices=[("default", "默认发布"), ("tencent_standard", "腾讯代码规范工具发布")],
                default="default",
                help_text="正式发布流程类型，决定灰度/预发布/全量的步骤与审批人",
                max_length=32,
                verbose_name="发布流程",
            ),
        ),
    ]
