# ------------------------------- builder container -------------------------------
FROM golang:1.18.10-bullseye as binary-builder

WORKDIR /src

COPY ./go.mod ./go.mod
COPY ./go.sum ./go.sum

RUN go mod download

COPY ./cmd ./cmd
COPY ./pkg ./pkg
COPY ./Makefile ./Makefile

RUN make build

# ------------------------------- shell provider container -------------------------------
FROM busybox:musl as busybox


# ------------------------------- runner container -------------------------------
FROM gcr.io/kaniko-project/executor:latest

RUN --mount=from=busybox:musl,dst=/busybox/ ["/busybox/bin/sh", "-c", "/busybox/bin/mkdir -p /tmp && /busybox/bin/chmod 777 /tmp"]

COPY --from=busybox /bin /busybox

COPY --from=binary-builder /src/bin/launcher /kaniko/blueking-launcher

ENV PATH /usr/local/bin:/kaniko:/busybox

RUN ["/busybox/mkdir", "-p", "/bin"]
RUN ["/busybox/ln", "-s", "/busybox/sh", "/bin/sh"]

ENTRYPOINT ["/kaniko/blueking-launcher"]
