#!/usr/bin/env bash
# 在 bin/compile 命令最后注入

declare build
export GOPATH="${GOPATH:-${HOME}/go}"

# post-compile 钩子调用保证能够找到编译后文件
env PATH="${GOPATH}/bin:${PATH}:${build}/bin" ${buildpack}/hooks/run_hook "post-compile" "${build}" "bin/post-compile"

# 将 GOPATH 的二进制复制到构建目录 go/bin 中
mkdir -p "${GOPATH}/bin"
gopath_bin=$(realpath "${GOPATH}/bin")
mkdir -p "go/bin"
go_bin=$(realpath "go/bin")
if [ "${gopath_bin}" != "${go_bin}" ]; then
    cp -u "${gopath_bin}"/* "${go_bin}" || true
fi

# 设置 ~/go 为运行时 GOPATH
mkdir -p "${build}/.profile.d"
cat > "${build}/.profile.d/gopath.sh" << EOF
GOPATH=\$HOME/go
PATH=\$PATH:\$GOPATH/bin:\$HOME/bin
EOF

# 清理代码文件以减少 slug 包体积
if [ "${WITH_CODE_FILES}" != "1" ]; then
    rm -rf vendor || true
    find . -type f \( -name '*.go' -o -name '*.s' -o -name '*.c' -o -name '*.cpp' \) -delete || true
fi