#!/usr/bin/env bash

name=$1
dir=$2

echo "Running ${name} hook"

cwd=$(pwd)
cd "${dir}" || exit 1
for ((i=3; i<=$#; i++)); do
    hook="${!i}"
    if [ -f "${hook}" ]; then
        echo "Running hook ${hook}"
        chmod +x "${hook}"
        "${hook}"
        code=$?
        if [ "${code}" = 0 ] ; then
            echo "Finished."
        else
            echo "Abort by exit code ${code}."
            exit "${code}"
        fi
    fi
done
cd "${cwd}" || exit 1
