# Generated by Django 3.2.12 on 2023-10-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_displayoptions_open_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketconfig',
            name='prefer_https',
            field=models.BooleanField(null=True, verbose_name='[deprecated] 仅为 False 时强制使用 http, 否则保持与集群 https_enabled 状态一致'),
        ),
    ]
