# Generated by Django 4.2.17 on 2025-03-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_displayoptions_tenant_id_marketconfig_tenant_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="region",
        ),
    ]
