# Generated by Django 4.2.17 on 2025-06-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_smartappextrainfo_artifact_metadata'),
        ('market', '0008_remove_tag_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_level', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='可用性保障等级')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('application', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='applications.application')),
                ('tag', models.ForeignKey(blank=True, default=None, help_text='按用途分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.tag', verbose_name='app分类')),
            ],
        ),
    ]
