# Generated by Django 3.2.12 on 2023-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_is_scene_app'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlogqueryconfig',
            name='process_type',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='进程类型(名称)'),
        ),
        migrations.AlterUniqueTogether(
            name='processlogqueryconfig',
            unique_together={('env', 'process_type')},
        ),
    ]
