/**
 * 导航元素埋点id集合
 */
import i18n from '@/language/i18n.js';
export const traceIds = {
  [i18n.t('概览')]: 'Overview',
  [i18n.t('应用引擎')]: 'AppEngine',
  [i18n.t('部署管理')]: 'Deploy',
  [i18n.t('进程管理')]: 'Processes',
  [i18n.t('日志查询')]: 'Logging',
  [i18n.t('结构化日志')]: 'StructuredLog',
  [i18n.t('标准输出日志')]: 'StdoutLog',
  [i18n.t('访问日志')]: 'AccessLog',
  [i18n.t('环境配置')]: 'EnvConfigs',
  [i18n.t('访问入口')]: 'Network&Domains',
  [i18n.t('代码检查')]: 'CodeAnalysis',
  [i18n.t('增强服务')]: 'Add-ons',
  [i18n.t('数据存储')]: 'Storages',
  [i18n.t('健康监测')]: 'HealthMonitoring',
  [i18n.t('模块管理')]: 'Modules',
  [i18n.t('权限管理')]: 'Permissions',
  [i18n.t('用户限制')]: 'UserWhitelists',
  [i18n.t('云API管理')]: 'BKCloudAPIs',
  [i18n.t('云 API 权限')]: 'CloudAPIPermissions',
  [i18n.t('监控告警')]: 'Monitoring',
  [i18n.t('告警记录')]: 'AlarmRecords',
  [i18n.t('数据统计')]: 'Statistics',
  [i18n.t('网站访问统计')]: 'Website',
  [i18n.t('访问日志统计')]: 'AccessLog',
  [i18n.t('自定义事件统计')]: 'CustomEvent',
  [i18n.t('应用推广')]: 'AppMarkets',
  [i18n.t('应用市场')]: 'Market',
  [i18n.t('基本设置')]: 'Settings',
  [i18n.t('基本信息')]: 'BasicInformation',
  [i18n.t('成员管理')]: 'Members',
  [i18n.t('文档管理')]: 'Document',
  [i18n.t('应用编排')]: 'AppOrchestration',
  [i18n.t('部署状态')]: 'DeploymentStatus',
  [i18n.t('镜像凭证')]: 'ImageCredentials',
  [i18n.t('镜像管理')]: 'Images',
  [i18n.t('访问统计')]: 'Statistics',
  [i18n.t('仪表盘')]: 'Dashboard',
  [i18n.t('访问管理')]: 'AccessManagement',
  [i18n.t('模块配置')]: 'ModuleSettings',
  [i18n.t('应用配置')]: 'APPSettings',
  [i18n.t('操作记录')]: 'OperationRecord',
  [i18n.t('访问地址')]: 'Address',
  [i18n.t('进程服务管理')]: 'ProcessServiceManagement',
  [i18n.t('IP限制')]: 'IPRestriction',
  [i18n.t('单据审批')]: 'Approval',
  [i18n.t('构建配置')]: 'BuildConfig',
  [i18n.t('进程配置')]: 'Processes',
  [i18n.t('环境变量')]: 'EnvVariables',
  [i18n.t('挂载卷')]: 'MountVolume',
  [i18n.t('可观测性')]: 'Observability',
  [i18n.t('更多配置')]: 'MoreConfig',
  [i18n.t('持久存储')]: 'PersistentStorage',
  [i18n.t('应用市场 (移动端)')]: 'APPMarket(Mobile)',
};
