# Generated by Django 3.2.25 on 2024-10-23 04:13

import blue_krill.models.fields
from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0016_auto_20240904_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevSandbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('alive', '存活'), ('expired', '过期'), ('error', '错误')], max_length=32, verbose_name='代码编辑器状态')),
                ('expire_at', models.DateTimeField(help_text='到期时间', null=True)),
                ('module', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
            ],
            options={
                'unique_together': {('module', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='CodeEditor',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('password', blue_krill.models.fields.EncryptField(help_text='登陆密码', max_length=32, verbose_name='登陆密码')),
                ('sandbox', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='code_editor', to='dev_sandbox.devsandbox')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
