# Generated by Django 3.2.25 on 2024-11-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devsandbox',
            old_name='expire_at',
            new_name='expired_at',
        ),
    ]
