# Generated by Django 3.2.25 on 2024-10-24 03:16

from django.db import migrations
import paasng.accessories.dev_sandbox.models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0002_rename_sandbox_codeeditor_dev_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsandbox',
            name='version_info',
            field=paasng.accessories.dev_sandbox.models.VersionInfoField(default=None, help_text='代码版本信息', null=True),
        ),
    ]
