# Generated by Django 3.2.25 on 2024-10-27 18:48

from django.db import migrations, models
import paasng.accessories.dev_sandbox.models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0003_devsandbox_version_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsandbox',
            name='code',
            field=models.CharField(default=paasng.accessories.dev_sandbox.models.generate_random_code, help_text='沙箱标识,模块下唯一', max_length=16),
        ),
        migrations.AlterField(
            model_name='devsandbox',
            name='status',
            field=models.CharField(choices=[('alive', '存活'), ('expired', '过期'), ('error', '错误')], max_length=32, verbose_name='沙箱状态'),
        ),
    ]
