# Generated by Django 4.2.16 on 2025-02-10 02:31

import blue_krill.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0003_codeeditor_tenant_id_devsandbox_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsandbox',
            name='token',
            field=blue_krill.models.fields.EncryptField(help_text='访问令牌', null=True),
        ),
        migrations.AlterField(
            model_name='codeeditor',
            name='password',
            field=blue_krill.models.fields.EncryptField(help_text='登录密码'),
        ),
        migrations.AlterField(
            model_name='devsandbox',
            name='status',
            field=models.CharField(max_length=32, verbose_name='沙箱状态'),
        ),
    ]
