# Generated by Django 4.2.16 on 2025-02-18 12:35

import blue_krill.models.fields
from django.db import migrations
import paasng.accessories.dev_sandbox.models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0003_codeeditor_tenant_id_devsandbox_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devsandbox',
            name='status',
        ),
        migrations.AddField(
            model_name='devsandbox',
            name='code_editor_config',
            field=paasng.accessories.dev_sandbox.models.CodeEditorConfigField(default=None, help_text='代码编辑器配置', null=True),
        ),
        migrations.AddField(
            model_name='devsandbox',
            name='token',
            field=blue_krill.models.fields.EncryptField(help_text='访问令牌', null=True),
        ),
        migrations.DeleteModel(
            name='CodeEditor',
        ),
    ]
