# Generated by Django 4.2.17 on 2025-07-08 03:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0004_remove_devsandbox_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsandbox',
            name='env_vars',
            field=jsonfield.fields.JSONField(default=list, help_text='环境变量列表'),
        ),
    ]
