# Generated by Django 4.2.17 on 2025-07-23 03:27

import blue_krill.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0004_remove_devsandbox_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsandbox',
            name='env_vars',
            field=blue_krill.models.fields.EncryptField(help_text='沙箱环境变量'),
        ),
    ]
