# Generated by Django 4.2.17 on 2025-07-18 03:43

import blue_krill.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0005_devsandbox_env_vars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devsandbox',
            name='env_vars',
            field=blue_krill.models.fields.EncryptField(blank=True, default=list, help_text='沙箱环境变量', null=True),
        ),
    ]
