# Generated by Django 4.2.17 on 2025-08-07 11:47

from django.db import migrations
import paasng.accessories.dev_sandbox.models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0005_devsandbox_env_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsandbox',
            name='enabled_addons_services',
            field=paasng.accessories.dev_sandbox.models.EnabledAddonsServicesField(default=list, help_text='用户复用的增强服务'),
        ),
    ]
