# Generated by Django 4.2.17 on 2025-07-08 09:32

import blue_krill.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0005_add_env_vars_to_devsandbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devsandbox',
            name='env_vars',
            field=blue_krill.models.fields.EncryptField(default=list, help_text='环境变量列表'),
        ),
    ]
