# Generated by Django 4.2.17 on 2025-08-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0005_devsandbox_env_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsandbox',
            name='enabled_addons_services',
            field=models.JSONField(default=list, help_text='沙箱使用的增强服务'),
        ),
    ]
