# Generated by Django 4.2.17 on 2025-08-22 02:38

from django.db import migrations, models
import paas_wl.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0006_devsandbox_enabled_addons_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevSandboxUserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paas_wl.utils.models.BkUserField(blank=True, db_index=True, help_text='沙箱绑定用户', max_length=64, null=True, unique=True)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('code_server_settings', models.JSONField(default=dict, help_text='用户沙箱 IDE 配置')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
