# Generated by Django 4.2.17 on 2025-08-13 06:40

from django.db import migrations, models
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sandbox', '0006_devsandbox_enabled_addons_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevSandboxUserPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('settings', models.JSONField(default=dict, help_text='用户沙箱 IDE 配置')),
            ],
        ),
        migrations.AddConstraint(
            model_name='devsandboxuserprefs',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_owner_prefs'),
        ),
    ]
