
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: custom-metrics-service-monitor
spec:
  endpoints:
    - path: /metrics
      port: metrics
      interval: 30s
      scrapeTimeout: 30s
  selector:
    matchLabels:
      control-plane: controller-manager
      app: bkapp-custom-metrics-service
