
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app: bkapp-custom-metrics-service
  name: custom-metrics-service
  namespace: system
spec:
  ports:
    - name: metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
  selector:
    control-plane: controller-manager
