# Generated by Django 3.2.12 on 2023-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkAppSecretInEnvVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bk_app_code', models.CharField(max_length=20, unique=True)),
                ('bk_app_secret_id', models.IntegerField(help_text='不存储密钥的信息，仅存储密钥 ID', verbose_name='应用密钥的 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
