"""The plan's stage-4 acceptance, end to end: one real turn, then read the repository back.

A real Runtime application, a real Agent, the existing fake model, and a real Forgejo. No paid
model is ever called. What this adds over ``tests/api/test_workspace_save.py`` is the transport:
a bare repository on the filesystem cannot show that the scoped token, the ``Authorization``
header, and the HTTP push path all work together underneath a run.

The stale-writer case is not repeated here; ``test_live_workspace.py`` already asserts that
Forgejo refuses a non-fast-forward push.
"""

from __future__ import annotations

import json
import time
from collections.abc import AsyncIterator, Callable, Iterator
from pathlib import Path
from typing import Any
from uuid import uuid4

import pytest
from fastapi.testclient import TestClient
from pydantic_ai.messages import ModelMessage
from pydantic_ai.models.function import AgentInfo, DeltaToolCall, DeltaToolCalls, FunctionModel

from app_spark_agent import settings
from app_spark_agent.git import GitWorkspace, RemoteConfig, WorkspaceSaver
from tests.api.support import MODEL_API_KEY, RUNTIME_TOKEN, build_test_client, run_turn
from tests.live_forgejo.conftest import open_workspace

pytestmark = pytest.mark.forgejo

WRITE_TOOL = "write_app"
NOTE = "generated by a live run\n"

# Generous: unlike the local-remote tests, this one waits on a real HTTP push to a container.
SAVE_TIMEOUT_SECONDS = 60.0


@pytest.fixture(autouse=True)
def runtime_credentials(monkeypatch: pytest.MonkeyPatch) -> None:
    """Give the Runtime the token its own client presents.

    ``tests/api`` gets this from its conftest, and these tests borrow that package's client and
    helpers without inheriting its fixtures -- so without this every request here is a 401.
    """
    monkeypatch.setattr(settings, "RUNTIME_TOKEN", RUNTIME_TOKEN)
    monkeypatch.setattr(settings, "MODEL_API_KEY", MODEL_API_KEY)
    # A short idle timeout in a developer `.env` would `os._exit` in the middle of a test.
    monkeypatch.setattr(settings, "IDLE_TIMEOUT_SECONDS", 0)


@pytest.fixture
def live_client(tmp_path: Path, project_remote: RemoteConfig) -> Iterator[TestClient]:
    """A started Runtime whose workspace is saved to a real Forgejo repository."""
    root = tmp_path / "runtime"
    root.mkdir()
    client = build_test_client(
        root,
        model=app_writing_model(),
        tools=[app_writer(root / "workspace")],
        make_saver=lambda workspace: WorkspaceSaver(
            open_workspace(workspace, project_remote),
            project_id="proj-live",
            retry_backoff_seconds=0.5,
        ),
    )
    # Entering the client runs the lifespan, which clones the provisioned repository into the
    # workspace before any run can touch a file.
    with client:
        yield client


def app_writing_model() -> FunctionModel:
    """A model that writes one file through a tool, then answers, then stops."""
    called = False

    async def stream(messages: list[ModelMessage], info: AgentInfo) -> AsyncIterator[str | DeltaToolCalls]:
        nonlocal called
        if called:
            yield "done"
            return
        called = True
        yield {0: DeltaToolCall(name=WRITE_TOOL, json_args=json.dumps({}), tool_call_id="call-1")}

    return FunctionModel(stream_function=stream)


def app_writer(workspace: Path) -> Callable[[], str]:
    """A tool that writes the file the test later expects to find in the repository."""

    def write_app() -> str:
        (workspace / "app.py").write_text(NOTE)
        return "written"

    write_app.__name__ = WRITE_TOOL
    return write_app


def wait_for_saved(client: TestClient, *, timeout: float = SAVE_TIMEOUT_SECONDS) -> dict[str, Any]:
    """Poll ``/health`` until the push has been confirmed, or fail the test."""
    deadline = time.monotonic() + timeout
    latest: dict[str, Any] = {}
    while time.monotonic() < deadline:
        latest = dict(client.get("/health").json())
        if not latest["workspace_save_pending"]:
            return latest
        time.sleep(0.2)
    raise AssertionError(f"the workspace never reached Forgejo: {latest.get('workspace')}")


def clone(remote: RemoteConfig, target: Path) -> GitWorkspace:
    """Take a fresh working copy of the remote, to read back what the push really stored."""
    workspace = open_workspace(target, remote)
    workspace.ensure_ready()
    return workspace


def test_one_turn_reaches_forgejo_and_can_be_cloned_back(
    live_client: TestClient, project_remote: RemoteConfig, tmp_path: Path
) -> None:
    conversation_id = str(uuid4())

    run_turn(live_client, conversation_id=conversation_id)

    saved = wait_for_saved(live_client)["workspace"]
    assert saved["state"] == "saved"
    assert saved["pushed_sha"] == saved["local_sha"]

    fresh = clone(project_remote, tmp_path / "clone")
    assert (fresh.path / "app.py").read_text() == NOTE
    message = fresh.runner.run("log", "-1", "--format=%B").stdout
    assert f"Conversation-Id: {conversation_id}" in message
    assert "Project-Id: proj-live" in message
    assert "Turn-Status: completed" in message


def test_the_checkpoint_tag_is_pinned_on_the_server(
    live_client: TestClient, project_remote: RemoteConfig, tmp_path: Path
) -> None:
    """The half of a checkpoint a bare local remote cannot vouch for.

    Pushing a tag goes through the same scoped token and the same HTTP path as pushing a branch,
    but it is a *different* ref namespace, and a repository whose permissions or protection rules
    allow one and not the other would fail here and nowhere else. Without the tag the commit is
    unreferenced, and an unreferenced commit is something the server may collect -- at which
    point the checkpoint points at nothing.
    """
    conversation_id = str(uuid4())

    run_turn(live_client, conversation_id=conversation_id)

    saved = wait_for_saved(live_client)["workspace"]
    fresh = clone(project_remote, tmp_path / "clone")
    fresh.runner.run("fetch", "origin", "--tags")
    tags = fresh.runner.run("tag", "--list", "app-spark/checkpoint/*").stdout.split()
    assert tags, "the turn's commit reached the server with no tag pinning it"
    pinned = fresh.runner.run("rev-parse", f"{tags[-1]}^{{commit}}").stdout.strip()
    assert pinned == saved["pushed_sha"]


def test_a_turn_that_wrote_nothing_adds_no_commit(live_client: TestClient) -> None:
    # The repository's history records what changed, not how many times the user pressed enter.
    conversation_id = str(uuid4())
    run_turn(live_client, conversation_id=conversation_id)
    first = wait_for_saved(live_client)["workspace"]["pushed_sha"]

    run_turn(live_client, conversation_id=conversation_id)

    assert wait_for_saved(live_client)["workspace"]["pushed_sha"] == first


def test_the_runtime_reports_a_save_it_has_not_confirmed_as_pending(
    live_client: TestClient, project_remote: RemoteConfig, tmp_path: Path
) -> None:
    # The distinction the whole stage exists to make: the turn's stream ending is not the same
    # event as the code being on the server, and `/health` is where the difference shows.
    conversation_id = str(uuid4())
    run_turn(live_client, conversation_id=conversation_id)

    document = wait_for_saved(live_client)
    assert document["workspace_persisted"] is True
    assert document["workspace"]["unsaved_seconds"] == 0.0
    assert document["workspace"]["needs_attention"] is False
