"""The workspace component against a real Git host.

What a bare repository on the filesystem cannot answer: whether the credential actually
authenticates over HTTP, whether the server refuses a non-fast-forward push on the working
branch, and whether a push really lands such that an unrelated empty directory can reproduce it.
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

import pytest

from app_spark_agent.git import GitAuthError, GitDivergedError, RemoteConfig
from tests.live_forgejo.conftest import open_workspace

pytestmark = pytest.mark.forgejo


def test_a_turn_is_reproduced_byte_for_byte_in_an_empty_workspace(project_remote: RemoteConfig, tmp_path: Path):
    """The acceptance for this stage: push, then clone somewhere else and get the same files."""
    workspace = open_workspace(tmp_path / "first", project_remote)
    assert workspace.ensure_ready() == "cloned"

    (workspace.path / "index.html").write_text("<h1>generated by a turn</h1>\n")
    (workspace.path / "app").mkdir()
    (workspace.path / "app" / "main.py").write_text("print('hello')\n")
    (workspace.path / ".env").write_text("APP_DEBUG=1\n")
    # Ignored by policy, so it must not make the trip.
    (workspace.path / "node_modules").mkdir()
    (workspace.path / "node_modules" / "big.js").write_text("x" * 100_000)

    committed = workspace.commit("turn 1", trailers={"Run-Id": "run-1"})
    assert committed is not None
    assert workspace.push() == committed

    second = open_workspace(tmp_path / "second", project_remote)
    assert second.ensure_ready() == "cloned"

    assert second.head() == committed
    assert (second.path / "index.html").read_text() == "<h1>generated by a turn</h1>\n"
    assert (second.path / "app" / "main.py").read_text() == "print('hello')\n"
    assert (second.path / ".env").read_text() == "APP_DEBUG=1\n"
    assert not (second.path / "node_modules").exists()


def test_a_second_turn_continues_from_the_first(project_remote: RemoteConfig, tmp_path: Path):
    workspace = open_workspace(tmp_path / "workspace", project_remote)
    workspace.ensure_ready()
    (workspace.path / "page.html").write_text("v1\n")
    first = workspace.commit("turn 1")
    workspace.push()

    (workspace.path / "page.html").write_text("v2\n")
    second = workspace.commit("turn 2")
    assert second != first
    workspace.push()

    read_back = open_workspace(tmp_path / "read-back", project_remote)
    read_back.ensure_ready()
    assert read_back.head() == second
    assert (read_back.path / "page.html").read_text() == "v2\n"


def test_a_turn_that_changed_nothing_pushes_nothing(project_remote: RemoteConfig, tmp_path: Path):
    workspace = open_workspace(tmp_path / "workspace", project_remote)
    workspace.ensure_ready()
    (workspace.path / "a.txt").write_text("only change\n")
    first = workspace.commit("turn 1")
    workspace.push()

    assert workspace.commit("turn 2") is None
    assert workspace.unpushed_commits() == 0
    assert workspace.remote_branch_head() == first


def test_a_bad_token_is_reported_as_an_auth_failure(project_remote: RemoteConfig, tmp_path: Path):
    """Distinct from "unreachable" because retrying will never fix it."""
    wrong = dataclasses.replace(project_remote, token="0000000000000000000000000000000000000000")
    workspace = open_workspace(tmp_path / "workspace", wrong)

    with pytest.raises(GitAuthError):
        workspace.remote_branch_head()


def test_the_server_refuses_a_push_that_is_behind(project_remote: RemoteConfig, tmp_path: Path):
    """A stale writer cannot overwrite the branch, and does not get to force it.

    This is the defence the whole design leans on: repository tokens are long-lived, so nothing
    stops an old Runtime from *trying*. What stops it is the remote.
    """
    first = open_workspace(tmp_path / "first", project_remote)
    first.ensure_ready()
    (first.path / "a.txt").write_text("from the first writer\n")
    first.commit("turn 1")
    first.push()

    # A replacement Runtime picks the work up and moves the branch on.
    second = open_workspace(tmp_path / "second", project_remote)
    second.ensure_ready()
    (second.path / "b.txt").write_text("from the replacement\n")
    second.commit("turn 2")
    winning = second.push()

    # The first one, still holding a valid token, tries to push its own history.
    (first.path / "c.txt").write_text("from the stale writer\n")
    first.commit("turn 2, from the stale writer")
    with pytest.raises(GitDivergedError):
        first.push()

    assert first.remote_branch_head() == winning
    survivor = open_workspace(tmp_path / "survivor", project_remote)
    survivor.ensure_ready()
    assert (survivor.path / "b.txt").exists()
    assert not (survivor.path / "c.txt").exists()


def test_a_restored_workspace_matches_an_older_checkpoint(project_remote: RemoteConfig, tmp_path: Path):
    workspace = open_workspace(tmp_path / "workspace", project_remote)
    workspace.ensure_ready()
    (workspace.path / "page.html").write_text("v1\n")
    checkpoint = workspace.commit("turn 1")
    workspace.push()
    (workspace.path / "page.html").write_text("v2\n")
    workspace.commit("turn 2")
    workspace.push()

    fresh = open_workspace(tmp_path / "fresh", project_remote)
    fresh.ensure_ready()
    assert checkpoint is not None
    fresh.restore(checkpoint)

    assert fresh.head() == checkpoint
    assert (fresh.path / "page.html").read_text() == "v1\n"
