# Generated by Django 4.2.17 on 2025-01-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2", "0002_bkappsecretinenvvar"),
    ]

    operations = [
        migrations.AddField(
            model_name="bkappsecretinenvvar",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
