# Generated by Django 4.2.16 on 2024-12-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_egressrule_egressspec'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionclusterstate',
            unique_together={('cluster_name', 'name')},
        ),
        migrations.RemoveField(
            model_name='regionclusterstate',
            name='region',
        ),
    ]
