# Generated by Django 3.2.25 on 2024-05-11 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_type'),
        ('bkmonitorv3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkmonitorspace',
            name='application',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bk_monitor_space', to='applications.application'),
        ),
    ]
