# Generated by Django 2.2.17 on 2021-05-24 11:16

import paas_wl.cluster.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='token_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='token_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ingress_config',
            field=paas_wl.cluster.models.IngressConfigField(),
        ),
    ]
