# Generated by Django 2.2.17 on 2021-12-14 02:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_auto_20210623_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='default_node_selector',
            field=jsonfield.fields.JSONField(default={}, help_text="default value for app's 'node_selector' field"),
        ),
        migrations.AddField(
            model_name='cluster',
            name='default_tolerations',
            field=jsonfield.fields.JSONField(default=[], help_text="default value for app's 'tolerations' field"),
        ),
    ]
