# Generated by Django 3.2.12 on 2022-09-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_auto_20211214_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='ca_data',
            field=models.TextField(null=True),
        ),
    ]
