# Generated by Django 3.2.12 on 2022-12-08 12:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_cluster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='feature_flags',
            field=jsonfield.fields.JSONField(default={}, help_text="cluster's feature flag set"),
        ),
    ]
