# Generated by Django 4.2.23 on 2025-09-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0002_auto_20201223_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentinstance",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
