#!/usr/bin/env bash

# remove all __pycache__ folders
find "${BUILD_DIR}" -name '__pycache__' -type d -exec rm -rf '{}' \; > /dev/null 2>&1 || true
# remove all .pyc files
find "${BUILD_DIR}" -name '*.pyc' -type f -delete > /dev/null 2>&1 || true
