#!/usr/bin/env bash

# 在安装 Python 环境之前执行

# 设置 vendor 到 PATH
export PATH=$PATH:$BUILDPACK_DIR/vendor/

# 为 heroku pip-install 提供可编辑目录
mkdir -p /app/.heroku/src

# 代替 runtime-fixer 来移除 runtime.txt 的空白
if [ -f runtime.txt ]; then
    sed -i '/^$/d' runtime.txt
fi

# remove unneeded steps
echo "#!/usr/bin/env bash" > "${BUILDPACK_DIR}/bin/steps/mercurial"
echo "#!/usr/bin/env bash" > "${BUILDPACK_DIR}/bin/steps/pylibmc"
echo "#!/usr/bin/env bash" > "${BUILDPACK_DIR}/bin/steps/cryptography"
echo "#!/usr/bin/env bash" > "${BUILDPACK_DIR}/bin/steps/geo-libs"
echo "#!/usr/bin/env bash" > "${BUILDPACK_DIR}/bin/steps/gdal"

# Installation will fail if you do not have permission to the directory /var/cache/apt/archives/partial/
echo "#!/usr/bin/env bash" > "${BUILDPACK_DIR}/bin/steps/sqlite3"
buildpack_sqlite3_install(){
    mkdir -p "${CACHE_DIR}/.heroku"
    echo "" > "${CACHE_DIR}/.heroku/python-sqlite3-version"
}

mkdir -p ~/.pip/
echo "[global]" > ~/.pip/pip.conf

# set pip index-url
if [ -n "${PIP_INDEX_URL}" ]; then
    echo "index-url = ${PIP_INDEX_URL}" >> ~/.pip/pip.conf
fi

# set pip extra-index-url
if [ -n "${PIP_EXTRA_INDEX_URL}" ]; then
    echo "extra-index-url = ${PIP_EXTRA_INDEX_URL}" >> ~/.pip/pip.conf
fi

# set pip trusted-host
if [ -n "${PIP_INDEX_HOST}" ]; then
    echo "trusted-host = ${PIP_INDEX_HOST}" >> ~/.pip/pip.conf
fi
