# Generated by Django 3.2.12 on 2022-08-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processspecplan',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='进程规格方案名称'),
        ),
        migrations.AlterUniqueTogether(
            name='processspecplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='processspecplan',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='processspecplan',
            name='region',
        ),
    ]
