# Generated by Django 4.2.17 on 2025-01-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="envroleprotection",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
