# Generated by Django 4.2.23 on 2026-02-10 15:32

import blue_krill.models.fields
from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0019_smartappextrainfo_artifact_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sandbox",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="租户内应用内唯一，未提供时自动生成",
                        max_length=64,
                        verbose_name="名称",
                    ),
                ),
                (
                    "snapshot",
                    models.CharField(
                        help_text="沙箱初始化使用的快照（镜像）",
                        max_length=128,
                        verbose_name="快照名字",
                    ),
                ),
                (
                    "snapshot_entrypoint",
                    models.JSONField(
                        default=list, help_text="沙箱快照启动时指定的 entrypoint"
                    ),
                ),
                (
                    "workspace",
                    models.CharField(
                        help_text="沙箱工作空间",
                        max_length=128,
                        null=True,
                        verbose_name="工作空间",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="沙箱所属目标区域（集群）",
                        max_length=32,
                        verbose_name="目标区域",
                    ),
                ),
                ("env_vars", models.JSONField(default=dict, verbose_name="环境变量")),
                (
                    "cpu",
                    models.DecimalField(
                        decimal_places=2,
                        default="2",
                        max_digits=10,
                        verbose_name="CPU 上限（核）",
                    ),
                ),
                (
                    "memory",
                    models.DecimalField(
                        decimal_places=2,
                        default="1",
                        max_digits=10,
                        verbose_name="内存上限（GB）",
                    ),
                ),
                (
                    "daemon_host",
                    models.CharField(
                        help_text="daemon 服务的访问地址, 格式如 127.0.0.1",
                        max_length=128,
                    ),
                ),
                (
                    "daemon_port",
                    models.IntegerField(
                        default=30000, help_text="daemon 服务的访问端口"
                    ),
                ),
                (
                    "daemon_token",
                    blue_krill.models.fields.EncryptField(
                        help_text="daemon 服务的访问 token"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=16, verbose_name="状态"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(null=True, verbose_name="启动时间"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(null=True, verbose_name="删除时间"),
                ),
                (
                    "creator",
                    paasng.utils.models.BkUserField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sandboxes",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
