# Generated by Django 4.2.23 on 2026-03-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='daemon_host',
            field=models.CharField(blank=True, default='', help_text='(deprecated) daemon 访问地址', max_length=128),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='daemon_port',
            field=models.IntegerField(default=0, help_text='(deprecated) daemon 访问端口'),
        ),
    ]
