# Generated by Django 4.2.23 on 2026-03-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandbox',
            name='daemon_host',
        ),
        migrations.RemoveField(
            model_name='sandbox',
            name='daemon_port',
        ),
    ]
