# Generated by Django 4.2.23 on 2026-03-22 02:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("agent_sandbox", "0002_remove_sandbox_daemon_host_alter_sandbox_daemon_port"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageBuild",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "app_code",
                    models.CharField(
                        help_text="发起构建的应用 ID", max_length=20
                    ),
                ),
                (
                    "source_url",
                    models.CharField(
                        help_text="源码压缩包的 URL 地址", max_length=1024
                    ),
                ),
                (
                    "image_name",
                    models.CharField(help_text="目标镜像名称", max_length=256),
                ),
                (
                    "image_tag",
                    models.CharField(help_text="目标镜像标签", max_length=128),
                ),
                (
                    "dockerfile_path",
                    models.CharField(
                        default="Dockerfile",
                        help_text="Dockerfile 相对路径",
                        max_length=512,
                    ),
                ),
                (
                    "docker_build_args",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Docker 构建参数（--build-arg）",
                    ),
                ),
                (
                    "prepared_source_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="预处理后上传到对象存储的源码包路径",
                        max_length=1024,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=16)),
                (
                    "build_logs",
                    models.TextField(
                        blank=True, default="", help_text="构建容器的标准输出日志"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="构建开始时间", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(help_text="构建完成时间", null=True),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
