# Generated by Django 4.2.23 on 2026-03-30 07:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_sandbox", "0003_imagebuild"),
    ]

    operations = [
        # Step 1: Rename the model (table stays the same, just the Django name changes)
        migrations.RenameModel(
            old_name="ImageBuild",
            new_name="ImageBuildRecord",
        ),
        # Step 2: Remove build_logs from the renamed table
        migrations.RemoveField(
            model_name="ImageBuildRecord",
            name="build_logs",
        ),
        # Step 3: Sync app_code help_text with current model definition
        migrations.AlterField(
            model_name="ImageBuildRecord",
            name="app_code",
            field=models.CharField(
                help_text="发起构建的应用 code，通常是 sysapi client 的 bk_app_code",
                max_length=20,
            ),
        ),
        # Step 4: Create the new ImageBuildLog table with FK to ImageBuildRecord
        migrations.CreateModel(
            name="ImageBuildLog",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "build",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="agent_sandbox.imagebuildrecord",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="构建容器的标准输出日志"
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
