# Generated by Django 4.2.23 on 2026-04-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0003_imagebuildrecord_imagebuildlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='expired_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='过期时间(预计删除时间)'),
        ),
    ]
