# Generated by Django 4.2.30 on 2026-05-12 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_reservedprefixauthcode'),
        ('agent_sandbox', '0004_sandbox_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='volume_mounts',
            field=models.JSONField(default=list, help_text='已解析的共享卷挂载列表，格式 [{"volume_id": str, "mount_path": str}]', verbose_name='挂载配置'),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='应用内唯一标识', max_length=64, verbose_name='卷名称')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='显示名称')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='agent_sandbox_volumes', to='applications.application')),
            ],
            options={
                'unique_together': {('tenant_id', 'application_id', 'name')},
            },
        ),
    ]
