# Generated by Django 4.2.30 on 2026-06-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0005_sandbox_volume_mounts_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(help_text='应用内唯一标识', max_length=256, verbose_name='卷名称'),
        ),
    ]
