# Generated by Django 4.2.30 on 2026-06-16 03:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_reservedprefixauthcode'),
        ('agent_sandbox', '0006_alter_volume_display_name_alter_volume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='cpu',
            field=models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=10, verbose_name='CPU 上限（核）'),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='memory',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=10, verbose_name='内存上限（GB）'),
        ),
        migrations.CreateModel(
            name='SandboxAppendConfig',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cpu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CPU 上限（核）')),
                ('memory', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='内存上限（GB）')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('application', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_append_config', to='applications.application')),
            ],
            options={
                'verbose_name': '沙箱附加配置',
            },
        ),
    ]
