# Generated by Django 4.2.30 on 2026-07-09 09:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0007_alter_sandbox_cpu_alter_sandbox_memory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeArtifact',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rel_path', models.CharField(max_length=700, verbose_name='volume 内相对路径')),
                ('mtime', models.CharField(help_text='RFC3339，与 daemon 返回一致', max_length=64, verbose_name='归档时文件 mtime')),
                ('size', models.BigIntegerField(verbose_name='归档时文件大小(字节)')),
                ('sha256', models.CharField(max_length=64, verbose_name='内容摘要')),
                ('bkrepo_key', models.CharField(max_length=1024, verbose_name='bkrepo 对象 key')),
                ('archived_at', models.DateTimeField(verbose_name='归档时间')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('volume', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='agent_sandbox.volume')),
            ],
            options={
                'unique_together': {('volume', 'rel_path')},
            },
        ),
    ]
