# Generated by Django 4.2.30 on 2026-08-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0008_volumeartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='workload_type',
            field=models.CharField(
                default='default',
                help_text='沙箱运行时类型：default（普通 Pod）/ sandbox_instance',
                max_length=16,
                verbose_name='工作负载类型',
            ),
        ),
    ]
