# Generated by Django 4.2.30 on 2026-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0008_volumeartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebuildrecord',
            name='image_type',
            field=models.CharField(default='agent_sandbox', help_text='镜像类型：agent_sandbox（Agent 沙箱镜像）/ sidecar（Sidecar 镜像）', max_length=16),
        ),
    ]
