# Generated by Django 5.2.15 on 2026-08-12 08:11

import paasng.utils.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0009_sandbox_workload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebuildlog',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='imagebuildrecord',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='sandboxappsettings',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='volumeartifact',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
