# Generated by Django 5.2.15 on 2026-08-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_sandbox", "0010_alter_imagebuildlog_uuid_alter_imagebuildrecord_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volume",
            name="shared_app_codes",
            field=models.JSONField(
                default=list,
                help_text="被授权后可把该 Volume 挂到自己的沙箱；空列表表示不跨应用共享，最多 50 个",
                verbose_name="共享给的应用 code 列表",
            ),
        ),
    ]
