# Generated by Django 5.2.15 on 2026-08-31 06:53

import uuid

import django.db.models.deletion
from django.db import migrations, models

import paasng.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_sandbox", "0011_volume_shared_app_codes"),
        ("applications", "0024_alter_application_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="E2BApiKey",
            fields=[
                (
                    "uuid",
                    paasng.utils.models.Char32UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", help_text="便于区分多枚 key", max_length=64, verbose_name="名称"
                    ),
                ),
                ("key_hash", models.CharField(max_length=64, unique=True, verbose_name="密钥摘要")),
                ("key_prefix", models.CharField(help_text="仅用于列表展示", max_length=16, verbose_name="密钥前缀")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("revoked_at", models.DateTimeField(null=True, verbose_name="吊销时间")),
                (
                    "owner",
                    paasng.utils.models.BkUserField(
                        blank=True, db_index=True, max_length=64, null=True, verbose_name="签发人"
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e2b_api_keys",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [models.Index(fields=["application", "enabled"], name="agent_sandb_applica_bb3785_idx")],
            },
        ),
    ]
