# Generated by Django 5.2.15 on 2026-08-31 07:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import paasng.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_sandbox", "0012_e2bapikey"),
        ("applications", "0024_alter_application_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="E2BSandbox",
            fields=[
                (
                    "uuid",
                    paasng.utils.models.Char32UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sandbox_id",
                    models.CharField(
                        help_text="gateway 返回的 ID", max_length=128, unique=True, verbose_name="沙箱 ID"
                    ),
                ),
                ("cluster_name", models.CharField(max_length=32, verbose_name="所属集群")),
                ("template_id", models.CharField(blank=True, default="", max_length=128, verbose_name="模板标识")),
                ("status", models.CharField(default="running", max_length=16, verbose_name="状态")),
                ("expired_at", models.DateTimeField(null=True, verbose_name="过期时间")),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e2b_sandboxes",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [models.Index(fields=["application", "status"], name="agent_sandb_applica_25b1ac_idx")],
            },
        ),
    ]
