# Generated by Django 5.2.15 on 2026-09-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0013_e2bsandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxappsettings',
            name='max_active_sandbox_count',
            field=models.PositiveIntegerField(blank=True, help_text='应用可同时存活的沙箱数量上限，未配置时回退到平台默认值', null=True, verbose_name='存活沙箱数量上限'),
        ),
    ]
