# Generated by Django 5.2.15 on 2026-09-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0013_e2bsandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='deleting_at',
            field=models.DateTimeField(null=True, verbose_name='开始删除时间'),
        ),
    ]
