# Generated by Django 5.2.15 on 2026-10-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sandbox', '0014_sandboxappsettings_max_active_sandbox_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='deleting_at',
            field=models.DateTimeField(null=True, verbose_name='开始删除时间'),
        ),
    ]
