# Generated by Django 6.0.8 on 2026-09-09 07:37

import blue_krill.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remote_id', models.BigIntegerField(blank=True, help_text='远端仓库数字 ID', null=True)),
                ('owner', models.CharField(help_text='远端组织名', max_length=64)),
                ('name', models.CharField(help_text='远端仓库名，与 Project ID 相同', max_length=64)),
                ('default_branch', models.CharField(default='main', max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('status_detail', models.TextField(blank=True, default='')),
                ('write_token', blue_krill.models.fields.EncryptField(blank=True, help_text='仓库范围的读写 token 明文（加密存储）', null=True)),
                ('write_token_id', models.PositiveIntegerField(blank=True, help_text='远端 token ID，用于撤销', null=True)),
                ('clone_url', models.CharField(blank=True, default='', max_length=512)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='git_repository', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
