# Generated by Django 6.0.8 on 2026-09-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_projectgitrepository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectgitrepository',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='projectgitrepository',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
