# Generated by Django 3.2.12 on 2023-06-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20220720_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodelrevision',
            name='deployed_value',
            field=models.JSONField(null=True, verbose_name='已部署的应用模型（JSON 格式）'),
        ),
    ]
