# Generated by Django 3.2.12 on 2023-10-21 11:39

from django.db import migrations, models
import paas_wl.bk_app.cnative.specs.models.network_config


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_configmapsource_mount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(unique=True, verbose_name='所属应用')),
                ('nameservers', paas_wl.bk_app.cnative.specs.models.network_config.NameServersField(default=list, help_text='k8s dnsConfig nameServers')),
                ('host_aliases', paas_wl.bk_app.cnative.specs.models.network_config.HostAliasesField(default=list, help_text='k8s hostAliases')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SvcDiscConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(unique=True, verbose_name='所属应用')),
                ('bk_saas', paas_wl.bk_app.cnative.specs.models.network_config.BkSaaSField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
