# Generated by Django 3.2.12 on 2023-12-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_configmapsource_mount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodeldeploy',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Deploy 名称'),
        ),
    ]
