# Generated by Django 3.2.12 on 2024-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0005_alter_appmodeldeploy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmapsource',
            name='module_id',
        ),
        migrations.AlterField(
            model_name='configmapsource',
            name='name',
            field=models.CharField(help_text='挂载资源名', max_length=63),
        ),
        migrations.AlterField(
            model_name='mount',
            name='source_type',
            field=models.CharField(choices=[('ConfigMap', 'Configmap'), ('PersistentVolumeClaim', 'Persistentvolumeclaim')], max_length=32),
        ),
        migrations.CreateModel(
            name='PersistentVolumeClaimSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(verbose_name='所属应用')),
                ('environment_name', models.CharField(choices=[('stag', '仅测试环境'), ('prod', '仅生产环境'), ('_global_', '所有环境')], max_length=16, verbose_name='环境名称')),
                ('name', models.CharField(help_text='挂载资源名', max_length=63)),
                ('storage', models.CharField(max_length=63)),
                ('storage_class_name', models.CharField(max_length=63)),
            ],
            options={
                'unique_together': {('name', 'application_id', 'environment_name')},
            },
        ),
    ]
