# Generated by Django 3.2.12 on 2024-03-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0006_auto_20240228_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persistentstoragesource',
            old_name='storage',
            new_name='storage_size',
        ),
    ]
