# Generated by Django 3.2.12 on 2024-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0007_rename_storage_persistentstoragesource_storage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentstoragesource',
            name='display_name',
            field=models.CharField(help_text='挂载资源展示名称', max_length=63, null=True),
        ),
    ]
