# Generated by Django 4.2.16 on 2025-01-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0008_auto_20240327_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmapsource',
            name='use_sub_path',
            field=models.BooleanField(default=False, help_text='是否使用子路径模式'),
        ),
    ]
