# Generated by Django 4.2.16 on 2025-02-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0009_appmodeldeploy_tenant_id_appmodelresource_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mount',
            name='sub_paths',
            field=models.JSONField(default=[], help_text='子路径配置'),
        ),
    ]
