# Generated by Django 4.2.23 on 2025-09-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specs", "0010_mount_sub_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="configmapsource",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="mount",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="persistentstoragesource",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
