# Generated by Django 4.2.23 on 2025-12-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_configmapsource_tenant_id_mount_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResQuotaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(max_length=64, unique=True, verbose_name='方案名称')),
                ('cpu_limits', models.CharField(max_length=8, verbose_name='CPU 限制')),
                ('memory_limits', models.CharField(max_length=8, verbose_name='内存限制')),
                ('cpu_requests', models.CharField(max_length=8, verbose_name='CPU 请求')),
                ('memory_requests', models.CharField(max_length=8, verbose_name='内存请求')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否为内置方案')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
