# Generated by Django 4.2.23 on 2026-03-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_configmapsource_tenant_id_mount_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configmapsource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configmapsource',
            name='pending_delete',
            field=models.BooleanField(default=False, help_text='是否标记为待删除状态'),
        ),
        migrations.AlterUniqueTogether(
            name='configmapsource',
            unique_together={('name', 'application_id', 'environment_name', 'pending_delete')},
        ),
    ]
