# Generated by Django 4.2.23 on 2026-03-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_configmapsource_tenant_id_mount_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configmapsource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configmapsource',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否已删除, 配合 pending_delete_envs 字段使用'),
        ),
        migrations.AddField(
            model_name='configmapsource',
            name='pending_delete_envs',
            field=models.JSONField(default=list, help_text='待删除的环境列表, 下次部署时删除对应环境的 k8s 资源'),
        ),
        migrations.AlterUniqueTogether(
            name='configmapsource',
            unique_together={('name', 'application_id', 'environment_name', 'is_deleted')},
        ),
    ]
