# Generated by Django 4.2.23 on 2026-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_configmapsource_tenant_id_mount_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountDeploymentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('module_id', models.UUIDField(verbose_name='所属模块')),
                ('environment_name', models.CharField(choices=[('stag', '仅测试环境'), ('prod', '仅生产环境'), ('_global_', '所有环境')], max_length=16, verbose_name='环境名称')),
                ('snapshot_data', models.JSONField(default=list)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
            ],
            options={
                'unique_together': {('module_id', 'environment_name')},
            },
        ),
    ]
