# Generated by Django 5.2.15 on 2026-08-12 08:11

import paas_wl.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0013_migrate_mount_snapshot_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodeldeploy',
            name='application_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='appmodeldeploy',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='appmodelresource',
            name='application_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='appmodelresource',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(unique=True, verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='appmodelrevision',
            name='application_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='appmodelrevision',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='configmapsource',
            name='application_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='configmapsource',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(null=True, verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='mountdeploymentsnapshot',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='persistentstoragesource',
            name='application_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='persistentstoragesource',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(null=True, verbose_name='所属模块'),
        ),
    ]
