# Generated by Django 3.2.12 on 2023-08-07 09:30

import blue_krill.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_cluster_feature_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='ca_data',
            field=blue_krill.models.fields.EncryptField(null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cert_data',
            field=blue_krill.models.fields.EncryptField(null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='key_data',
            field=blue_krill.models.fields.EncryptField(null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='token_value',
            field=blue_krill.models.fields.EncryptField(null=True),
        ),
    ]
