# Generated by Django 4.2.16 on 2024-12-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0010_alter_cluster_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="exposed_url_type",
            field=models.IntegerField(default=1, verbose_name="应用的访问地址类型"),
        ),
    ]
