# Generated by Django 4.2.16 on 2024-12-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_clusterallocationpolicy_cluster_available_tenant_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiserver',
            name='overridden_hostname',
        ),
    ]
