# Generated by Django 4.2.16 on 2024-12-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0012_clusterallocationpolicy_cluster_available_tenant_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='assert_hostname',
            field=models.JSONField(default=None, help_text='TLS 验证主机名', null=True),
        ),
    ]
