# Generated by Django 4.2.16 on 2025-01-14 02:30

from django.db import migrations, models
import django.db.models.deletion
import paas_wl.infras.cluster.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0015_remove_apiserver_overridden_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='exposed_url_type',
            field=models.IntegerField(default=1, help_text='应用的访问地址类型'),
        ),
        migrations.AlterField(
            model_name='clusterallocationpolicy',
            name='allocation_policy',
            field=paas_wl.infras.cluster.models.AllocationPolicyField(default=None, help_text='统一分配策略', null=True),
        ),
        migrations.AlterField(
            model_name='clusterallocationpolicy',
            name='allocation_precedence_policies',
            field=paas_wl.infras.cluster.models.AllocationPrecedencePoliciesField(default=list, help_text='规则分配优先策略'),
        ),
        migrations.CreateModel(
            name='ClusterComponent',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='组件名称', max_length=64)),
                ('required', models.BooleanField(help_text='是否为必要组件')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cluster.cluster')),
            ],
            options={
                'unique_together': {('cluster', 'name')},
            },
        ),
    ]
