# Generated by Django 4.2.16 on 2025-01-17 01:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0016_apiserver_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterComponent',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='组件名称', max_length=64)),
                ('required', models.BooleanField(help_text='是否为必要组件')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cluster.cluster')),
            ],
            options={
                'unique_together': {('cluster', 'name')},
            },
        ),
    ]
