# Generated by Django 4.2.16 on 2025-03-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0020_initial_cluster_allocation_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="region",
        ),
    ]
