# Generated by Django 4.2.16 on 2025-04-15 08:27

import blue_krill.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0021_remove_cluster_is_default_remove_cluster_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterAppImageRegistry",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("host", models.CharField(help_text="镜像仓库地址", max_length=256)),
                (
                    "skip_tls_verify",
                    models.BooleanField(
                        default=False, help_text="是否跳过 TLS 证书验证"
                    ),
                ),
                (
                    "namespace",
                    models.CharField(help_text="镜像仓库命名空间", max_length=128),
                ),
                (
                    "username",
                    models.CharField(help_text="镜像仓库用户名", max_length=64),
                ),
                (
                    "password",
                    blue_krill.models.fields.EncryptField(help_text="镜像仓库密码"),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
                (
                    "cluster",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_image_registry",
                        to="cluster.cluster",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
