# Generated by Django 4.2.23 on 2025-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0022_clusterappimageregistry"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterelasticsearchconfig",
            name="ca_certs",
            field=models.TextField(help_text="ES 集群 CA 证书", null=True),
        ),
        migrations.AddField(
            model_name="clusterelasticsearchconfig",
            name="client_cert",
            field=models.TextField(help_text="ES 集群客户端证书", null=True),
        ),
        migrations.AddField(
            model_name="clusterelasticsearchconfig",
            name="client_key",
            field=models.TextField(help_text="ES 集群客户端密钥", null=True),
        ),
        migrations.AddField(
            model_name="clusterelasticsearchconfig",
            name="verify_certs",
            field=models.BooleanField(default=False, help_text="是否验证 TLS 证书"),
        ),
    ]
