# Generated by Django 5.2.15 on 2026-08-12 08:11

import paas_wl.utils.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0023_clusterelasticsearchconfig_ca_certs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiserver',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='clusterallocationpolicy',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='clusterappimageregistry',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='clustercomponent',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='clusterelasticsearchconfig',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
