# Generated by Django 5.2.15 on 2026-08-31 07:05

import uuid

import blue_krill.models.fields
import django.db.models.deletion
from django.db import migrations, models

import paas_wl.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("cluster", "0024_alter_apiserver_uuid_alter_cluster_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterE2BConfig",
            fields=[
                (
                    "uuid",
                    paas_wl.utils.models.Char32UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "control_plane_url",
                    models.CharField(
                        help_text="e2b-gateway 地址，负责沙箱创建、销毁等管理操作，仅 apiserver 侧访问", max_length=256
                    ),
                ),
                (
                    "data_plane_address",
                    models.CharField(
                        help_text="供 SDK 直连 e2b-sandbox-gateway 的对外地址，负责命令执行与文件读写，会改写进创建响应的域名字段",
                        max_length=256,
                    ),
                ),
                (
                    "api_key",
                    blue_krill.models.fields.EncryptField(
                        help_text="该集群 gateway 的真实凭证，仅 apiserver 持有，不下发给用户"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, help_text="是否参与 e2b 沙箱调度")),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
                (
                    "cluster",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="e2b_config", to="cluster.cluster"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
