# Generated by Django 3.2.12 on 2023-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_customcollectorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcollectorconfig',
            name='log_paths',
            field=models.JSONField(verbose_name='日志文件的绝对路径，可使用 通配符;'),
        ),
    ]
