"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except
in compliance with the License. You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing permissions and
limitations under the License.

We undertake not to change the open source license (MIT license) applicable
to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.12 on 2023-11-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_auto_20231019_0944'),
        ('log', '0003_customcollectorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcollectorconfig',
            name='collector_config_id',
            field=models.BigIntegerField(db_index=True, help_text='采集配置ID', verbose_name='采集配置ID'),
        ),
        migrations.AlterField(
            model_name='customcollectorconfig',
            name='log_paths',
            field=models.JSONField(verbose_name='日志文件的绝对路径，可使用 通配符;'),
        ),
        migrations.AlterField(
            model_name='customcollectorconfig',
            name='name_en',
            field=models.CharField(db_index=True, help_text='5-50个字符，仅包含字母数字下划线, 查询索引是 name_en-*', max_length=50, verbose_name='自定义采集项名称'),
        ),
        migrations.AlterUniqueTogether(
            name='customcollectorconfig',
            unique_together={('module', 'name_en')},
        ),
    ]
