# Generated by Django 3.2.12 on 2023-12-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20231103_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcollectorconfig',
            name='is_builtin',
            field=models.BooleanField(default=False, verbose_name='是否为内置采集项'),
        ),
        migrations.AddField(
            model_name='customcollectorconfig',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
