# Generated by Django 4.2.16 on 2025-02-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0006_auto_20231212_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcollectorconfig",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="processlogqueryconfig",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
