# Generated by Django 4.2.23 on 2026-04-07 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_customcollectorconfig_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLogConfig',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(default='default', help_text='本条数据的所属租户', max_length=32, unique=True, verbose_name='租户 ID')),
                ('storage_cluster_id', models.IntegerField(help_text='指定该租户日志存储的 ES 集群', verbose_name='日志平台存储集群 ID')),
                ('retention', models.IntegerField(verbose_name='日志保存时间（天）')),
                ('es_shards', models.IntegerField(verbose_name='ES 索引分片数')),
                ('storage_replicas', models.IntegerField(verbose_name='存储副本数')),
                ('time_zone', models.IntegerField(help_text='日志时间字段解析时区，如 8 代表 UTC+8', verbose_name='时区')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
