# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0009_init_tenantlogconfig_from_deprecated_bklog_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantlogconfig",
            name="shared_bk_biz_id",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="启用 ENABLE_SHARED_BK_LOG_INDEX 时生效, 共享采集项所挂载的蓝鲸 CMDB 业务 ID (非 space_id)",
                null=True,
                verbose_name="平台级共享采集项所属业务 ID",
            ),
        ),
    ]
