# Generated by Django 4.2.23 on 2026-04-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0009_init_tenantlogconfig_from_deprecated_bklog_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantlogconfig",
            name="shared_bk_biz_id",
            field=models.IntegerField(
                default=None,
                help_text="仅启用 ENABLE_SHARED_BK_LOG_INDEX 时生效",
                null=True,
                verbose_name="共享采集项所挂载的 CMDB 业务 ID",
            ),
        ),
    ]
