# Generated by Django 3.2.12 on 2023-08-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220509_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(max_length=64, unique=True, verbose_name='分类名称'),
        ),
    ]
