# Generated by Django 4.2.16 on 2025-01-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecategory_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='display_name',
            field=models.CharField(default='', max_length=64, verbose_name='方案展示名称'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tenant_id',
            field=models.CharField(default='default', help_text='所属租户', max_length=128),
        ),
    ]
