# Generated by Django 4.2.16 on 2025-02-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecategory_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='precreatedinstance',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID'),
        ),
        migrations.AddField(
            model_name='resourceid',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID'),
        ),
    ]
