# Generated by Django 4.2.16 on 2025-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecategory_name_en'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plan',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('service', 'name', 'tenant_id')},
        ),
    ]
