# Generated by Django 4.2.16 on 2025-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_plan_unique_together_plan_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='服务名称'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='region',
        ),
    ]
