# Generated by Django 4.2.23 on 2026-02-10 12:19

from django.db import migrations, models
import jsonfield.fields
import paasng.accessories.services.constants


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_unique_together_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precreatedinstance',
            name='allocation_type',
            field=models.CharField(default=paasng.accessories.services.constants.PreCreatedInstanceAllocationType['FIFO'], help_text='分配类型', max_length=32),
        ),
        migrations.AddField(
            model_name='precreatedinstance',
            name='binding_policy',
            field=jsonfield.fields.JSONField(default=dict, help_text='绑定策略, 如 {app_code, module_name, env_name}'),
        ),
    ]
