# Generated by Django 4.2.23 on 2026-02-04 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_unique_together_alter_service_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCreatedInstanceBindingPolicy',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app_code', models.CharField(max_length=20, null=True)),
                ('module_name', models.CharField(max_length=20, null=True)),
                ('env', models.CharField(max_length=16, null=True)),
                ('tenant_id', models.CharField(default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('pre_created_instance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binding_policies', to='services.precreatedinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
