# Generated by Django 5.2.15 on 2026-08-12 08:11

import jsonfield.fields
import paasng.utils.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_precreatedinstance_allocation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='precreatedinstance',
            name='binding_policy',
            field=jsonfield.fields.JSONField(default=dict, help_text='绑定策略, 每个维度为列表, 如 {"app_code": ["myapp"], "module_name": ["default"], "env_name": ["prod"]}'),
        ),
        migrations.AlterField(
            model_name='precreatedinstance',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
