# Generated by Django 4.2.23 on 2026-02-06 08:19

from django.db import migrations, models
import paasng.accessories.services.constants


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_precreatedinstancebindingpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='precreatedinstance',
            name='allocation_type',
            field=models.CharField(default=paasng.accessories.services.constants.PreCreatedInstanceAllocationType['FIFO'], help_text='分配类型', max_length=32),
        ),
    ]
