# -*- coding: utf-8 -*-
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.

# Generated by Django 3.2.12 on 2022-09-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bk_plugins', '0003_auto_20220118_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkPluginTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='插件使用方名称', max_length=32, unique=True, verbose_name='分类名称')),
                ('code_name', models.CharField(help_text='分类英文名称，可替代主键使用', max_length=32, unique=True, verbose_name='分类英文名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bkpluginprofile',
            name='tag',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='选填', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bk_plugins.bkplugintag', verbose_name='插件分类'),
        ),
    ]
