# Generated by Django 3.2.12 on 2023-01-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_plugins', '0005_auto_20221202_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkplugintag',
            name='priority',
            field=models.IntegerField(default=0, help_text='数字越大，优先级越高', verbose_name='优先级'),
        ),
    ]
