# Generated by Django 4.2.17 on 2025-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugins", "0008_bkplugintag_init"),
    ]

    operations = [
        migrations.AddField(
            model_name="bkpluginprofile",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
