# Generated by Django 3.2.12 on 2023-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_alter_template_repo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('normal', '普通应用'), ('scene', '场景模板'), ('plugin', '插件模板')], max_length=16, verbose_name='模板类型'),
        ),
    ]
