# Generated by Django 3.2.12 on 2023-05-15 09:45

from django.db import migrations, models
import paasng.engine.constants


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_auto_20230510_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='runtime_type',
            field=models.CharField(default=paasng.engine.constants.RuntimeType['BUILDPACK'], max_length=32, verbose_name='运行时类型'),
        ),
    ]
