# Generated by Django 4.2.17 on 2025-01-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_appdashboardtemplate_appdashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="appalertrule",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="appdashboard",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
