FROM golang:1.25.4-alpine3.22

WORKDIR /workspace

# Install build dependencies (required by Makefile commands)
RUN apk add --no-cache git curl bash make

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy source code and Makefile
COPY . .

# Pre-install tools for development and testing
RUN make ginkgo golangci-lint
