# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making
蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
Copyright (C) 2017-2022THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.

We undertake not to change the open source license (MIT license) applicable

to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 2.2.17 on 2020-11-27 02:50

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import paasng.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
        ('applications', '0002_auto_20201127_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('env_variables', jsonfield.fields.JSONField(blank=True, default=[], verbose_name='environment variables')),
                ('runtime', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='runtime config')),
                ('scripts', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='scripts')),
                ('environments', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='environment specified configs')),
                ('plugins', jsonfield.fields.JSONField(blank=True, default=[], verbose_name='extra plugins')),
                ('deployment', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='declarative_config', to='engine.Deployment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='ID of application')),
                ('name', models.CharField(max_length=20, verbose_name='application name')),
                ('basic_info', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='basic information')),
                ('market', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='market specs')),
                ('services', jsonfield.fields.JSONField(blank=True, default=[], verbose_name='service specs')),
                ('plugins', jsonfield.fields.JSONField(blank=True, default=[], verbose_name='extra plugins')),
                ('is_creation', models.BooleanField(default=False, verbose_name='whether current descritpion creates an application')),
                ('application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='declarative_config', to='applications.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
