# Generated by Django 3.2.12 on 2023-05-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_config_mount_app_log_to_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='image',
            field=models.TextField(default='', help_text='运行 Build 的镜像地址, 对于构件类型为 image 的 Build 该值同时也是构建产物', null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='build',
            name='artifact_deleted',
            field=models.BooleanField(default=False, help_text='slug/镜像是否已被清理'),
        ),
        migrations.AlterField(
            model_name='build',
            name='slug_path',
            field=models.TextField(help_text='slug path 形如 {region}/home/{name}:{branch}:{revision}/push', null=True),
        ),
        migrations.AlterField(
            model_name='buildprocess',
            name='image',
            field=models.CharField(help_text='builder image', max_length=512, null=True),
        ),
    ]
