# Generated by Django 3.2.12 on 2023-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230527_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='image_id',
            field=models.CharField(help_text='镜像摘要(例如, sha256:xxx)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='artifact_type',
            field=models.CharField(default=paas_wl.platform.applications.constants.ArtifactType['SLUG'],
                                   help_text='构建产物类型', max_length=16),
        ),
    ]
