# Generated by Django 3.2.12 on 2023-07-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230629_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='application_id',
            field=models.UUIDField(null=True, verbose_name='所属应用'),
        ),
        migrations.AddField(
            model_name='build',
            name='module_id',
            field=models.UUIDField(null=True, verbose_name='所属模块'),
        ),
        migrations.AddField(
            model_name='buildprocess',
            name='application_id',
            field=models.UUIDField(null=True, verbose_name='所属应用'),
        ),
        migrations.AddField(
            model_name='buildprocess',
            name='module_id',
            field=models.UUIDField(null=True, verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='build',
            name='app',
            field=models.ForeignKey(help_text='[deprecated] wl_app 外键', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.app'),
        ),
        migrations.AlterField(
            model_name='buildprocess',
            name='app',
            field=models.ForeignKey(help_text='[deprecated] wl_app 外键', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.app'),
        ),
    ]
