# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.

# Generated by Django 3.2.12 on 2023-10-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0010_remove_module_runtime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProcessSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, verbose_name='进程名称')),
                ('proc_command', models.TextField(help_text='进程启动命令(包含完整命令和参数的字符串), 只能与 command/args 二选一', null=True)),
                ('command', models.JSONField(default=None, help_text='容器执行命令', null=True)),
                ('args', models.JSONField(default=None, help_text='命令参数', null=True)),
                ('port', models.IntegerField(help_text='容器端口', null=True)),
                ('image', models.CharField(help_text='容器镜像, 仅用于 v1alpha1 的云原生应用', max_length=255, null=True)),
                ('image_pull_policy', models.CharField(choices=[('Always', 'Always'), ('IfNotPresent', 'If not present'), ('Never', 'Never')], default="IfNotPresent", help_text='镜像拉取策略(仅用于 v1alpha1 的云原生应用)', max_length=20)),
                ('image_credential_name', models.CharField(help_text='镜像拉取凭证名(仅用于 v1alpha1 的云原生应用)', max_length=64, null=True)),
                ('target_replicas', models.IntegerField(default=1, verbose_name='期望副本数')),
                ('target_status', models.CharField(default='start', max_length=32, verbose_name='期望状态')),
                ('plan_name', models.CharField(help_text='仅存储方案名称', max_length=32)),
                ('autoscaling', models.BooleanField(default=False, verbose_name='是否启用自动扩缩容')),
                ('scaling_config', models.JSONField(default={}, verbose_name='自动扩缩容配置')),
                ('module', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='process_specs', to='modules.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
