# Generated by Django 3.2.12 on 2023-10-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_remove_module_runtime_type'),
        ('bkapp_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprocessspec',
            name='module',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='process_specs', to='modules.module'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprocessspec',
            unique_together={('module', 'name')},
        ),
    ]
