"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except
in compliance with the License. You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing permissions and
limitations under the License.

We undertake not to change the open source license (MIT license) applicable
to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.12 on 2023-10-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_auto_20231019_0944'),
        ('bkapp_model', '0004_auto_20231019_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDeployHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('pre-release-hook', '部署前置钩子')], help_text='钩子类型', max_length=20)),
                ('proc_command', models.TextField(help_text='进程启动命令(包含完整命令和参数的字符串), 只能与 command/args 二选一', null=True)),
                ('command', models.JSONField(default=None, help_text='容器执行命令', null=True)),
                ('args', models.JSONField(default=None, help_text='命令参数', null=True)),
                ('enabled', models.BooleanField(default=False, help_text='是否已开启')),
                ('module', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_hooks', to='modules.module')),
            ],
            options={
                'unique_together': {('module', 'type')},
            },
        ),
    ]
