# Generated by Django 3.2.12 on 2023-10-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0006_auto_20231020_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processspecenvoverlay',
            name='autoscaling',
            field=models.BooleanField(null=True, verbose_name='是否启用自动扩缩容'),
        ),
        migrations.AlterField(
            model_name='processspecenvoverlay',
            name='plan_name',
            field=models.CharField(blank=True, help_text='仅存储方案名称', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='processspecenvoverlay',
            name='target_replicas',
            field=models.IntegerField(null=True, verbose_name='期望副本数'),
        ),
    ]
