# Generated by Django 3.2.12 on 2023-10-26 08:49

from django.db import migrations, models
import paasng.platform.bkapp_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0007_auto_20231024_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(unique=True, verbose_name='所属应用')),
                ('nameservers', paasng.platform.bkapp_model.models.NameServersField(default=list, help_text='k8s dnsConfig nameServers')),
                ('host_aliases', paasng.platform.bkapp_model.models.HostAliasesField(default=list, help_text='k8s hostAliases')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SvcDiscConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(unique=True, verbose_name='所属应用')),
                ('bk_saas', paasng.platform.bkapp_model.models.BkSaaSField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
