# Generated by Django 3.2.12 on 2023-11-27 12:39
import json
import logging

from django.db import migrations

from paasng.platform.bkapp_model.entities import AutoscalingConfig

logger = logging.getLogger(__name__)


def fix_invalid_module_process_spec_scaling_config_data(apps, schema_editor):
    """修复 ModuleProcessSpec.scaling_config 为空时, 由历史代码写入数据库的不规范数据
    已知的脏数据有: 空字符串 '' 和 空字典 '{}'
    """

    ModuleProcessSpec = apps.get_model("bkapp_model", "ModuleProcessSpec")
    qs = (
        ModuleProcessSpec.objects.using(schema_editor.connection.alias)
        .all()
        .extra({"raw_scaling_config": "scaling_config"})
        .values("id", "raw_scaling_config")
    ).iterator()

    for item in qs:
        try:
            _ = AutoscalingConfig(**json.loads(item["raw_scaling_config"]))
        except (json.JSONDecodeError, TypeError):
            logger.warning(
                "scaling_config(%s) of obj<%s> is invalid, set it to None",
                item["raw_scaling_config"],
                item["id"],
            )
            ModuleProcessSpec.objects.using(schema_editor.connection.alias).filter(id=item["id"]).update(
                scaling_config=None
            )


def fix_invalid_env_overlay_scaling_config_data(apps, schema_editor):
    """修复 ProcessSpecEnvOverlay.scaling_config 为空时, 由历史代码写入数据库的不规范数据
    已知的脏数据有: 空字符串 '' 和 空字典 '{}'
    """
    ProcessSpecEnvOverlay = apps.get_model("bkapp_model", "ProcessSpecEnvOverlay")
    qs = (
        ProcessSpecEnvOverlay.objects.using(schema_editor.connection.alias)
        .all()
        .extra({"raw_scaling_config": "scaling_config"})
        .values("id", "raw_scaling_config")
    ).iterator()

    for item in qs:
        try:
            _ = AutoscalingConfig(**json.loads(item["raw_scaling_config"]))
        except (json.JSONDecodeError, TypeError):
            logger.warning(
                "scaling_config(%s) of obj<%s> is invalid, set it to None",
                item["raw_scaling_config"],
                item["id"],
            )
            ProcessSpecEnvOverlay.objects.using(schema_editor.connection.alias).filter(id=item["id"]).update(
                scaling_config=None
            )


class Migration(migrations.Migration):

    dependencies = [
        ("bkapp_model", "0009_auto_20231123_2051"),
    ]

    operations = [
        migrations.RunPython(fix_invalid_module_process_spec_scaling_config_data),
        migrations.RunPython(fix_invalid_env_overlay_scaling_config_data),
    ]
