# Generated by Django 3.2.25 on 2024-06-12 01:58

from django.db import migrations
import paasng.platform.bkapp_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0011_auto_20240407_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprocessspec',
            name='probes',
            field=paasng.platform.bkapp_model.models.ProbeSetField(default=None, null=True, verbose_name='容器探针配置'),
        ),
    ]
