# Generated by Django 3.2.25 on 2024-07-18 12:51

from django.db import migrations
import paasng.platform.bkapp_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0012_moduleprocessspec_probes'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprocessspec',
            name='services',
            field=paasng.platform.bkapp_model.models.ProcServicesField(default=None, help_text='进程服务列表', null=True),
        ),
    ]
