# Generated by Django 3.2.25 on 2024-09-04 06:39

from django.db import migrations, models
import django.db.models.deletion
import paasng.platform.bkapp_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_auto_20240904_1439'),
        ('bkapp_model', '0014_migrate_proc_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprocessspec',
            name='port',
            field=models.IntegerField(help_text='[deprecated] 容器端口', null=True),
        ),
        migrations.CreateModel(
            name='ObservabilityConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('monitoring', paasng.platform.bkapp_model.models.MonitoringField(default=None, null=True, verbose_name='监控配置')),
                ('last_monitoring', paasng.platform.bkapp_model.models.MonitoringField(default=None, null=True, verbose_name='最近的一次监控配置')),
                ('module', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
