# Generated by Django 4.2.17 on 2025-05-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkapp_model", "0018_bkappmanagedfields_tenant_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessServicesFlag",
        ),
    ]
