# Generated by Django 4.2.17 on 2025-07-14 13:36

from django.db import migrations
import paasng.platform.bkapp_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0019_delete_processservicesflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprocessspec',
            name='components',
            field=paasng.platform.bkapp_model.models.ComponentsField(default=None, null=True, verbose_name='组件配置'),
        ),
    ]
