# Generated by Django 4.2.17 on 2025-07-07 03:50

from django.db import migrations, models
import paasng.platform.bkapp_model.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0019_delete_processservicesflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprocessspec',
            name='components',
            field=paasng.platform.bkapp_model.models.ComponentsField(default=None, null=True, verbose_name='组件配置'),
        ),
        migrations.CreateModel(
            name='ProcessComponent',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32, verbose_name='类型')),
                ('version', models.CharField(max_length=32, verbose_name='版本')),
                ('enabled', models.BooleanField(default=True, help_text='是否可用', verbose_name='是否可用')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('docs_url', models.CharField(max_length=255, null=True, verbose_name='文档地址')),
                ('properties_json_schema', models.JSONField(default=None, null=True, verbose_name='组件配置规范')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
            ],
            options={
                'unique_together': {('type', 'version')},
            },
        ),
    ]
