# Generated by Django 4.2.23 on 2025-09-18 15:15

from django.db import migrations
import paasng.platform.bkapp_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0020_moduleprocessspec_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprocessspec',
            name='resources',
            field=paasng.platform.bkapp_model.models.ResourcesField(default=None, null=True, verbose_name='资源配置'),
        ),
        migrations.AddField(
            model_name='processspecenvoverlay',
            name='resources',
            field=paasng.platform.bkapp_model.models.ResourcesField(default=None, null=True, verbose_name='资源配置'),
        ),
    ]
