# Generated by Django 4.2.23 on 2025-11-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0020_moduleprocessspec_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='processspecenvoverlay',
            name='admin_res_config',
            field=models.JSONField(blank=True, help_text='格式: {"limits": {"cpu": "2", "memory": "2Gi"}, "requests": {"cpu": "1", "memory": "1Gi"} }', null=True, verbose_name='管理员配置的资源限制'),
        ),
    ]
