# Generated by Django 4.2.23 on 2026-01-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0023_init_resquotaplan_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processspecenvoverlay',
            name='override_proc_res',
            field=models.JSONField(blank=True, null=True, verbose_name='管理员配置的资源配额'),
        ),
    ]
