# Generated by Django 4.2.23 on 2026-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0023_init_resquotaplan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='processspecenvoverlay',
            name='override_plan_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='管理员配置的资源配额方案名称'),
        ),
    ]
