# Generated by Django 4.2.23 on 2026-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0024_alter_processspecenvoverlay_override_proc_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='processspecenvoverlay',
            name='override_plan_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='资源配额方案名称'),
        ),
        migrations.AddField(
            model_name='processspecenvoverlay',
            name='override_resources',
            field=models.JSONField(blank=True, null=True, verbose_name='资源配额'),
        ),
        migrations.AlterField(
            model_name='processspecenvoverlay',
            name='override_proc_res',
            field=models.JSONField(blank=True, null=True, verbose_name='[deprecated] 资源配额配置, 已不再使用'),
        ),
    ]
