# Generated by Django 4.2.23 on 2026-03-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkapp_model', '0026_migrate_override_proc_res_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprocessspec',
            name='graceful_shutdown_seconds',
            field=models.IntegerField(null=True, verbose_name='优雅终止时间(秒)'),
        ),
    ]
