# Generated by Django 5.2.15 on 2026-09-07 07:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bkapp_model", "0028_add_some_builtin_resquotaplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="resquotaplan",
            name="allowed_app_codes",
            field=jsonfield.fields.JSONField(default=list, verbose_name="专用应用列表"),
        ),
    ]
