# Generated by Django 4.2.16 on 2025-02-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam_adaptor", "0002_iam_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugingrademanager",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="pluginusergroup",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
