apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-spark-ui.fullname" . }}
  labels:
    {{- include "app-spark-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app-spark-ui.selectorLabels" . | nindent 4 }}
