# Generated by Django 3.2.12 on 2023-03-28 09:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20220830_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='processspec',
            name='autoscaling',
            field=models.BooleanField(default=False, verbose_name='是否启用自动扩缩容'),
        ),
        migrations.AddField(
            model_name='processspec',
            name='scaling_config',
            field=jsonfield.fields.JSONField(default={}, verbose_name='自动扩缩容配置'),
        ),
    ]
