# Generated by Django 3.2.12 on 2023-10-13 03:15

from django.db import migrations, models
import paas_wl.workloads.release_controller.constants


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_processprobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='processspec',
            name='args',
            field=models.JSONField(default=None, help_text='命令参数', null=True),
        ),
        migrations.AddField(
            model_name='processspec',
            name='command',
            field=models.JSONField(default=None, help_text='容器执行命令', null=True),
        ),
        migrations.AddField(
            model_name='processspec',
            name='image',
            field=models.CharField(help_text='容器镜像, 仅用于 v1alpha1 的云原生应用', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processspec',
            name='image_credential_name',
            field=models.CharField(help_text='镜像拉取凭证名(仅用于 v1alpha1 的云原生应用)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='processspec',
            name='image_pull_policy',
            field=models.CharField(choices=[('Always', 'Always'), ('IfNotPresent', 'If not present'), ('Never', 'Never')], default=paas_wl.workloads.release_controller.constants.ImagePullPolicy['IF_NOT_PRESENT'], help_text='镜像拉取策略(仅用于 v1alpha1 的云原生应用)', max_length=20),
        ),
        migrations.AddField(
            model_name='processspec',
            name='port',
            field=models.IntegerField(help_text='容器端口', null=True),
        ),
        migrations.AddField(
            model_name='processspec',
            name='proc_command',
            field=models.TextField(help_text='进程启动命令(包含完整命令和参数的字符串), 只能与 command/args 二选一', null=True),
        ),
    ]
