# Generated by Django 3.2.12 on 2023-11-23 12:51

from django.db import migrations
import paas_wl.bk_app.processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_auto_20231013_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processspec',
            name='scaling_config',
            field=paas_wl.bk_app.processes.models.AutoscalingConfigField(null=True, verbose_name='自动扩缩容配置'),
        ),
    ]
