# Generated by Django 4.2.16 on 2025-01-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0008_auto_20240407_1349"),
    ]

    operations = [
        migrations.AddField(
            model_name="processspec",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
