# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
# Copyright (C) Tencent. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.

"""Create the admin, service account and App-Spark organisation.

Safe to run repeatedly: existing users, the organisation and team membership
are left alone. Generated passwords are written to ``secrets/credentials.env``
and never printed.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from app_spark_forgejo.common import (
    ADMIN_EMAIL,
    ADMIN_USERNAME,
    DEFAULT_BRANCH,
    ORG_NAME,
    SERVICE_EMAIL,
    SERVICE_USERNAME,
    base_url,
    credentials_from_env,
    credentials_path,
    forgejo_cli,
    load_or_create_credentials,
    request_json,
    wait_ready,
)


def _user_exists_output(result_stderr: str, result_stdout: str) -> bool:
    text = f"{result_stdout}\n{result_stderr}".lower()
    return "already exists" in text or "user already exist" in text


def create_user(*, username: str, password: str, email: str, admin: bool) -> None:
    if os.environ.get("FORGEJO_SKIP_CLI_USER_CREATE") == "1":
        return
    args = [
        "admin",
        "user",
        "create",
        "--username",
        username,
        "--password",
        password,
        "--email",
        email,
        "--must-change-password=false",
    ]
    if admin:
        args.append("--admin")
    result = forgejo_cli(*args)
    if result.returncode == 0:
        return
    if _user_exists_output(result.stderr, result.stdout):
        return
    # Do not echo the password-bearing command; the CLI itself does not print it.
    sys.stderr.write(result.stderr or result.stdout or "forgejo admin user create failed\n")
    raise SystemExit(result.returncode)


def ensure_org(admin_password: str) -> None:
    status, body = request_json(
        "POST",
        "/api/v1/orgs",
        username=ADMIN_USERNAME,
        password=admin_password,
        payload={
            "username": ORG_NAME,
            "full_name": "App-Spark",
            "visibility": "private",
            "repo_admin_change_team_access": True,
        },
    )
    if status in {201, 422}:
        # 422 is "org already exists" on Forgejo.
        return
    raise SystemExit(f"creating organisation {ORG_NAME} failed: HTTP {status} {body}")


def _owners_team_id(admin_password: str) -> int:
    status, body = request_json(
        "GET",
        f"/api/v1/orgs/{ORG_NAME}/teams",
        username=ADMIN_USERNAME,
        password=admin_password,
    )
    if status != 200 or not isinstance(body, list):
        raise SystemExit(f"listing teams failed: HTTP {status} {body}")
    for team in body:
        if isinstance(team, dict) and team.get("name") == "Owners":
            team_id = team.get("id")
            if isinstance(team_id, int):
                return team_id
    raise SystemExit(f"organisation {ORG_NAME} has no Owners team")


def ensure_service_account_owns_org(admin_password: str) -> None:
    team_id = _owners_team_id(admin_password)
    status, body = request_json(
        "PUT",
        f"/api/v1/teams/{team_id}/members/{SERVICE_USERNAME}",
        username=ADMIN_USERNAME,
        password=admin_password,
    )
    if status not in {204, 200}:
        raise SystemExit(f"adding {SERVICE_USERNAME} to Owners failed: HTTP {status} {body}")


def write_api_settings_snippet(service_password: str) -> None:
    """Write a YAML snippet the API service can copy. Password stays in secrets/."""
    snippet = (
        "# Generated by app-spark-forgejo init. Do not commit. Copy into settings_local.yaml.\n"
        "REPO_SERVER:\n"
        "  type: forgejo\n"
        f"  base_url: {base_url()}\n"
        f"  clone_url: {base_url()}\n"
        f"  org: {ORG_NAME}\n"
        f"  service_account: {SERVICE_USERNAME}\n"
        f"  service_account_password: {service_password}\n"
        f"  default_branch: {DEFAULT_BRANCH}\n"
        "  commit_author_name: App-Spark\n"
        "  commit_author_email: app-spark@localhost.invalid\n"
    )
    path = credentials_path().with_name("app-spark-api.yaml")
    path.write_text(snippet)
    path.chmod(0o600)


def initialise() -> None:
    wait_ready()
    creds = load_or_create_credentials()
    create_user(
        username=ADMIN_USERNAME,
        password=creds["ADMIN_PASSWORD"],
        email=ADMIN_EMAIL,
        admin=True,
    )
    create_user(
        username=SERVICE_USERNAME,
        password=creds["SERVICE_ACCOUNT_PASSWORD"],
        email=SERVICE_EMAIL,
        admin=False,
    )
    ensure_org(creds["ADMIN_PASSWORD"])
    ensure_service_account_owns_org(creds["ADMIN_PASSWORD"])
    if credentials_from_env() is None:
        write_api_settings_snippet(creds["SERVICE_ACCOUNT_PASSWORD"])
        secrets = Path(credentials_path())
        print(f"Forgejo initialised. Credentials: {secrets} (not printed).")
    else:
        print("Forgejo initialised. Credentials taken from the environment (not written).")
    print(f"Host API: {base_url()}")
    print("Compose-network API: http://server:3000")
