# Generated by Django 4.2.17 on 2025-03-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingress", "0009_alter_appdomain_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appdomain",
            name="region",
        ),
        migrations.RemoveField(
            model_name="appdomaincert",
            name="region",
        ),
        migrations.RemoveField(
            model_name="appdomainsharedcert",
            name="region",
        ),
        migrations.RemoveField(
            model_name="appsubpath",
            name="region",
        ),
    ]
