# Generated by Django 4.2.17 on 2025-05-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingress",
            "0010_remove_appdomain_region_remove_appdomaincert_region_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appdomain",
            name="protocol",
            field=models.CharField(default="http", max_length=16),
        ),
    ]
