# Generated by Django 5.2.15 on 2026-08-12 08:11

import paas_wl.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0011_appdomain_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='module_id',
            field=paas_wl.utils.models.Char32UUIDField(help_text='关联的模块 ID'),
        ),
    ]
