# -*- coding: utf-8 -*-
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.

# Generated by Django 2.2.17 on 2020-11-27 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import paasng.accessories.smart_advisor.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployFailurePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=paasng.accessories.smart_advisor.constants.DeployFailurePatternType(1))),
                ('value', models.CharField(max_length=2048)),
                ('tag_str', models.CharField(max_length=128)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentaryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('short_description', models.CharField(blank=True, max_length=512)),
                ('location', models.URLField()),
                ('affinity_tags', jsonfield.fields.JSONField(blank=True, default=[], max_length=256)),
                ('anti_affinity_tags', jsonfield.fields.JSONField(blank=True, default=[], max_length=256)),
                ('priority', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AppModuleTagRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_str', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tag_rels', to='modules.Module')),
            ],
            options={
                'unique_together': {('module', 'tag_str')},
            },
        ),
    ]
