# Generated by Django 3.2.12 on 2023-08-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_advisor', '0002_auto_20220518_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentarylink',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='documentarylink',
            name='short_description_zh_cn',
            field=models.CharField(blank=True, max_length=512, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='documentarylink',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='documentarylink',
            name='title_zh_cn',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
    ]
