# Generated by Django 4.2.17 on 2025-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_advisor", "0003_auto_20230807_1727"),
    ]

    operations = [
        migrations.AddField(
            model_name="appmoduletagrel",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
