# Generated by Django 3.2.12 on 2024-02-22 09:12

from django.db import migrations
import paasng.platform.declarative.models


class Migration(migrations.Migration):

    dependencies = [
        ('declarative', '0003_auto_20220506_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentdescription',
            name='spec',
            field=paasng.platform.declarative.models.BkAppSpecField(default=None, null=True, verbose_name='bkapp.spec'),
        ),
    ]
