# Generated by Django 4.2.16 on 2024-11-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("declarative", "0004_deploymentdescription_spec"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deploymentdescription",
            name="scripts",
        ),
    ]
