# Generated by Django 4.2.17 on 2025-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("declarative", "0005_remove_deploymentdescription_scripts"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdescription",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="deploymentdescription",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
