# Generated by Django 4.2.16 on 2025-02-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationLatestOp',
        ),
    ]
