# Generated by Django 4.2.17 on 2025-04-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationLatestOp',
        ),
    ]
