# Generated by Django 6.0.8 on 2026-08-18 11:38

import app_spark_api.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', app_spark_api.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('role', models.IntegerField(default=2)),
                ('feature_flags', models.TextField(blank=True, null=True)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
