# Generated by Django 3.2.12 on 2023-07-21 08:40

from django.db import migrations, models
import paas_wl.cnative.specs.models.mount


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_appmodelrevision_deployed_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('module_id', models.UUIDField(verbose_name='所属模块')),
                ('environment_name', models.CharField(choices=[('stag', '仅测试环境'), ('prod', '仅生产环境'), ('_global_', '所有环境')], max_length=16, verbose_name='环境名称')),
                ('name', models.CharField(max_length=63)),
                ('mount_path', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('ConfigMap', 'Configmap')], max_length=32)),
                ('source_config', paas_wl.cnative.specs.models.mount.SourceConfigField()),
            ],
            options={
                'unique_together': {('module_id', 'mount_path', 'environment_name')},
            },
        ),
        migrations.CreateModel(
            name='ConfigMapSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('module_id', models.UUIDField(verbose_name='所属模块')),
                ('environment_name', models.CharField(choices=[('stag', '仅测试环境'), ('prod', '仅生产环境'), ('_global_', '所有环境')], max_length=16, verbose_name='环境名称')),
                ('name', models.CharField(max_length=63)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('module_id', 'name', 'environment_name')},
            },
        ),
    ]
