# Generated by Django 4.2.23 on 2025-09-04 06:08

from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBuildLog',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartBuildRecord',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source_origin', models.CharField(help_text='源码来源类型，如：源码包、代码仓库', max_length=32)),
                ('package_name', models.CharField(blank=True, default='', help_text='源码包名称', max_length=128)),
                ('app_code', models.CharField(help_text='应用的唯一标识', max_length=64)),
                ('artifact_url', models.URLField(blank=True, default='', help_text='s-mart 构建产物地址', max_length=2048)),
                ('status', models.CharField(default='pending', help_text='s-mart 构建任务运行状态', max_length=12)),
                ('err_detail', models.TextField(blank=True, help_text='构建失败时的错误详情', null=True)),
                ('start_time', models.DateTimeField(help_text='构建任务起始时间', null=True)),
                ('end_time', models.DateTimeField(help_text='构建任务结束时间', null=True)),
                ('operator', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('stream', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='smart_build', to='smart_builder.smartbuildlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartBuildPhase',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32, verbose_name='创建阶段类型')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='状态')),
                ('start_time', models.DateTimeField(null=True, verbose_name='阶段开始时间')),
                ('complete_time', models.DateTimeField(null=True, verbose_name='阶段完成时间')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('smart_build', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='smart_builder.smartbuildrecord', verbose_name='关联创建操作')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('smart_build', 'type')},
            },
        ),
        migrations.CreateModel(
            name='SmartBuildLogLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stream', models.CharField(max_length=16)),
                ('line', models.TextField()),
                ('smart_build_log', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='smart_builder.smartbuildlog')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SmartBuildStep',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='步骤名称')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='状态')),
                ('start_time', models.DateTimeField(null=True, verbose_name='阶段开始时间')),
                ('complete_time', models.DateTimeField(null=True, verbose_name='阶段完成时间')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('phase', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='smart_builder.smartbuildphase', verbose_name='关联阶段')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('phase', 'name')},
            },
        ),
    ]
