# Generated by Django 4.2.23 on 2025-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbuildrecord',
            name='app_version',
            field=models.CharField(blank=True, help_text='应用版本号', max_length=32),
        ),
    ]
