# Generated by Django 4.2.23 on 2025-11-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_smartbuildrecord_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbuildrecord',
            name='sha256_signature',
            field=models.CharField(default='', help_text='源码包的 sha256 值', max_length=64),
        ),
    ]
