# Generated by Django 4.2.23 on 2025-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_smartbuildrecord_sha256_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbuildrecord',
            name='packaging_version',
            field=models.CharField(default='v2', help_text='打包版本, 如: v1、v2', max_length=8),
        ),
    ]
