# Generated by Django 3.2.12 on 2022-11-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0009_application_is_scene_app'),
        ('modules', '0006_auto_20220509_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alert_code', models.CharField(help_text='alert rule code e.g. high_cpu_usage', max_length=64)),
                ('display_name', models.CharField(max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('threshold_expr', models.CharField(max_length=64)),
                ('receivers', models.JSONField(default=list)),
                ('environment', models.CharField(max_length=16, verbose_name='部署环境')),
                ('application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='applications.application')),
                ('module', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='modules.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
