# Generated by Django 3.2.12 on 2024-04-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0002_auto_20201209_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteserviceengineappattachment',
            name='write_instance_credentials_to_env',
            field=models.BooleanField(default=True, verbose_name='写入环境变量'),
        ),
        migrations.AddField(
            model_name='serviceengineappattachment',
            name='write_instance_credentials_to_env',
            field=models.BooleanField(default=False, verbose_name='写入环境变量'),
        ),
    ]
