# Generated by Django 3.2.12 on 2024-04-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0002_auto_20201209_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteserviceengineappattachment',
            name='credentials_enabled',
            field=models.BooleanField(default=True, verbose_name='是否使用凭证'),
        ),
        migrations.AddField(
            model_name='serviceengineappattachment',
            name='credentials_enabled',
            field=models.BooleanField(default=True, verbose_name='是否使用凭证'),
        ),
    ]
