# Generated by Django 3.2.12 on 2024-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0003_auto_20240411_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteserviceengineappattachment',
            name='credentials_disabled',
        ),
        migrations.RemoveField(
            model_name='serviceengineappattachment',
            name='credentials_disabled',
        ),
        migrations.AddField(
            model_name='remoteserviceengineappattachment',
            name='credentials_enabled',
            field=models.BooleanField(default=True, verbose_name='是否使用凭证'),
        ),
        migrations.AddField(
            model_name='serviceengineappattachment',
            name='credentials_enabled',
            field=models.BooleanField(default=True, verbose_name='是否使用凭证'),
        ),
    ]
