# Generated by Django 4.2.16 on 2024-12-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicehub", "0004_auto_20240412_1723"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceBindingPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("service_id", models.UUIDField(unique=True, verbose_name="增强服务 ID")),
                (
                    "service_type",
                    models.CharField(
                        help_text="远程或本地", max_length=16, verbose_name="增强服务类型"
                    ),
                ),
                ("type", models.CharField(max_length=16, verbose_name="策略类型")),
                ("data", models.JSONField(default={}, help_text="策略数据")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceBindingPrecedencePolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("service_id", models.UUIDField(db_index=True, verbose_name="增强服务 ID")),
                (
                    "service_type",
                    models.CharField(
                        help_text="远程或本地", max_length=16, verbose_name="增强服务类型"
                    ),
                ),
                ("cond_type", models.CharField(max_length=16, verbose_name="条件类型")),
                ("cond_data", models.JSONField(default={}, verbose_name="条件值")),
                ("type", models.CharField(max_length=16, verbose_name="策略类型")),
                ("data", models.JSONField(default={}, help_text="策略值")),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=0, help_text="值越大，优先级越高", verbose_name="优先级"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
