# Generated by Django 4.2.16 on 2024-12-03 10:04

from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_applicationdeploymentmoduleorder'),
        ('modules', '0016_auto_20240904_1439'),
        ('engine', '0022_builtinconfigvar'),
        ('services', '0006_alter_servicecategory_name_en'),
        ('servicehub', '0004_auto_20240412_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnboundServiceEngineAppAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('environment', models.CharField(max_length=16, verbose_name='部署环境')),
                ('status', models.IntegerField(choices=[(1, 'Unbound service instance with engine app'), (2, 'Recycled service instance')], default=1, help_text='1 已解绑; 2 已回收;', verbose_name='解绑状态')),
                ('application', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application', verbose_name='蓝鲸应用')),
                ('engine_app', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.engineapp', verbose_name='蓝鲸引擎应用')),
                ('module', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.module', verbose_name='蓝鲸应用模块')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='增强服务')),
                ('service_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.serviceinstance', verbose_name='增强服务实例')),
            ],
            options={
                'verbose_name': '本地已解绑增强服务',
            },
        ),
        migrations.CreateModel(
            name='UnboundRemoteServiceEngineAppAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('environment', models.CharField(max_length=16, verbose_name='部署环境')),
                ('service_id', models.UUIDField(verbose_name='远程增强服务 ID')),
                ('service_instance_id', models.UUIDField(null=True, verbose_name='远程增强服务实例 ID')),
                ('status', models.IntegerField(choices=[(1, 'Unbound service instance with engine app'), (2, 'Recycled service instance')], default=1, help_text='1 已解绑; 2 已回收;', verbose_name='解绑状态')),
                ('application', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application', verbose_name='蓝鲸应用')),
                ('engine_app', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.engineapp', verbose_name='蓝鲸引擎应用')),
                ('module', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.module', verbose_name='蓝鲸应用模块')),
            ],
            options={
                'verbose_name': '远程已解绑增强服务',
            },
        ),
    ]
