# Generated by Django 4.2.16 on 2024-12-11 07:40

from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecategory_name_en'),
        ('engine', '0023_remove_deployment_hooks_remove_deployment_procfile'),
        ('servicehub', '0004_auto_20240412_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnboundServiceEngineAppAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('credentials_enabled', models.BooleanField(default=True, verbose_name='是否使用凭证')),
                ('engine_app', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.engineapp', verbose_name='蓝鲸引擎应用')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.plan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='增强服务')),
                ('service_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.serviceinstance', verbose_name='增强服务实例')),
            ],
            options={
                'verbose_name': '本地已解绑增强服务',
                'unique_together': {('service', 'engine_app')},
            },
        ),
        migrations.CreateModel(
            name='UnboundRemoteServiceEngineAppAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('service_id', models.UUIDField(verbose_name='远程增强服务 ID')),
                ('plan_id', models.UUIDField(verbose_name='远程增强服务 Plan ID')),
                ('service_instance_id', models.UUIDField(null=True, verbose_name='远程增强服务实例 ID')),
                ('credentials_enabled', models.BooleanField(default=True, verbose_name='是否使用凭证')),
                ('engine_app', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='unbound_remote_service_attachment', to='engine.engineapp', verbose_name='蓝鲸引擎应用')),
            ],
            options={
                'verbose_name': '远程已解绑增强服务',
                'unique_together': {('service_id', 'engine_app')},
            },
        ),
    ]
