# Generated by Django 4.2.16 on 2025-01-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0007_init_service_binding_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebindingpolicy',
            name='tenant_id',
            field=models.CharField(default='default', help_text='所属租户', max_length=128),
        ),
        migrations.AddField(
            model_name='servicebindingprecedencepolicy',
            name='tenant_id',
            field=models.CharField(default='default', help_text='所属租户', max_length=128),
        ),
        migrations.AlterField(
            model_name='servicebindingpolicy',
            name='service_id',
            field=models.UUIDField(verbose_name='增强服务 ID'),
        ),
        migrations.AlterUniqueTogether(
            name='servicebindingpolicy',
            unique_together={('service_id', 'tenant_id')},
        ),
    ]
