# Generated by Django 4.2.16 on 2025-03-12 07:49

import logging

from django.db import migrations
from django.utils import translation
from django.conf import settings

from paasng.accessories.servicehub.manager import mixed_service_mgr
from paasng.accessories.servicehub.binding_policy.manager import ServiceBindingPolicyManager
from paasng.core.tenant.user import DEFAULT_TENANT_ID

logger = logging.getLogger(__name__)


def init_service_binding_policy(apps, schema_editor):
    """
    Initialize the service binding policy for all services.

    Background:
    Service binding scheme has been changed from implicit filtering to explicit
    allocation based on ServiceBindingPolicy and ServiceBindingPrecedencePolicy.

    Purpose:
    This migration reads existing plan data and creates default ServiceBindingPolicy
    model to ensure that existing services can continue to function properly.

    Special Considerations:
    - The migration will skip initialization if any binding policies already exist,
      to prevent overwriting existing configurations.
    """
    ServiceBindingPolicy = apps.get_model("servicehub", "ServiceBindingPolicy")
    ServiceBindingPrecedencePolicy = apps.get_model("servicehub", "ServiceBindingPrecedencePolicy")

    # Check if either policy already exists
    if ServiceBindingPolicy.objects.exists() or ServiceBindingPrecedencePolicy.objects.exists():
        logger.info("Service binding policy already exists, skip init")
        return

    # mixed_service_mgr.list() 会调用 django.utils.translation.get_language()
    # 虽然配置了 settings.LANGUAGE_CODE 但是必须在国际化中间件 LocaleMiddleware 调用后才会有值
    with translation.override(settings.LANGUAGE_CODE):
        for service in mixed_service_mgr.list():
            logger.info("Init service(%s) binding policy for service", service.name)
            plans = service.get_plans()
            ServiceBindingPolicyManager(service, DEFAULT_TENANT_ID).set_static(plans)
            logger.info("Service(%s) binding policy init done", service.name)


class Migration(migrations.Migration):
    dependencies = [
        ('servicehub', '0009_servicebindingpolicy_tenant_id_and_more'),
    ]

    operations = [
        migrations.RunPython(init_service_binding_policy),
    ]
