# Generated by Django 4.2.16 on 2025-03-12 07:49
"""
本意用于通过 plans 自动生成 Service Binding Policies，为临时修复。
因此将该 migration 文件置为空，并且逻辑迁移至 apiserver/paasng/paasng/platform/scheduler/jobs.py 文件的 init_service_binding_policy 方法中处理。
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('servicehub', '0009_servicebindingpolicy_tenant_id_and_more'),
    ]

    operations = [
    ]
