# Generated by Django 4.2.16 on 2025-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0010_init_service_binding_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebindingpolicy',
            name='service_id',
            field=models.UUIDField(verbose_name='增强服务 ID'),
        ),
    ]
