# Generated by Django 4.2.17 on 2025-03-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicehub", "0011_alter_servicebindingpolicy_service_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultPolicyCreationRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("service_id", models.UUIDField(unique=True, verbose_name="增强服务 ID")),
                (
                    "service_type",
                    models.CharField(
                        help_text="远程或本地", max_length=16, verbose_name="增强服务类型"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
