# Generated by Django 4.2.17 on 2025-03-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicehub", "0011_alter_servicebindingpolicy_service_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceBindingPolicyAutoBindRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("service_id", models.UUIDField(db_index=True, verbose_name="增强服务 ID")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
