# Generated by Django 4.2.17 on 2025-05-26 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0012_defaultpolicycreationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAllocationPolicy',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service_id', models.UUIDField(db_index=True, verbose_name='增强服务 ID')),
                ('type', models.CharField(help_text='分配策略类型', max_length=32)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
            ],
            options={
                'unique_together': {('tenant_id', 'service_id')},
            },
        ),
    ]
