# Generated by Django 4.2.30 on 2026-07-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0014_add_matcher_to_svc_binding_precedence_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebindingprecedencepolicy',
            name='cond_data',
        ),
        migrations.RemoveField(
            model_name='servicebindingprecedencepolicy',
            name='cond_type',
        ),
    ]
