# Generated by Django 5.2.15 on 2026-08-12 08:11

import paasng.utils.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0015_remove_servicebindingprecedencepolicy_cond_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpolicycreationrecord',
            name='service_id',
            field=paasng.utils.models.Char32UUIDField(unique=True, verbose_name='增强服务 ID'),
        ),
        migrations.AlterField(
            model_name='remoteserviceengineappattachment',
            name='plan_id',
            field=paasng.utils.models.Char32UUIDField(verbose_name='远程增强服务 Plan ID'),
        ),
        migrations.AlterField(
            model_name='remoteserviceengineappattachment',
            name='service_id',
            field=paasng.utils.models.Char32UUIDField(verbose_name='远程增强服务 ID'),
        ),
        migrations.AlterField(
            model_name='remoteserviceengineappattachment',
            name='service_instance_id',
            field=paasng.utils.models.Char32UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='remoteservicemoduleattachment',
            name='service_id',
            field=paasng.utils.models.Char32UUIDField(verbose_name='远程增强服务 ID'),
        ),
        migrations.AlterField(
            model_name='serviceallocationpolicy',
            name='service_id',
            field=paasng.utils.models.Char32UUIDField(db_index=True, verbose_name='增强服务 ID'),
        ),
        migrations.AlterField(
            model_name='serviceallocationpolicy',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='servicebindingpolicy',
            name='service_id',
            field=paasng.utils.models.Char32UUIDField(verbose_name='增强服务 ID'),
        ),
        migrations.AlterField(
            model_name='servicebindingprecedencepolicy',
            name='service_id',
            field=paasng.utils.models.Char32UUIDField(db_index=True, verbose_name='增强服务 ID'),
        ),
        migrations.AlterField(
            model_name='sharedserviceattachment',
            name='service_id',
            field=paasng.utils.models.Char32UUIDField(verbose_name='增强服务 ID'),
        ),
        migrations.AlterField(
            model_name='unboundremoteserviceengineappattachment',
            name='service_id',
            field=paasng.utils.models.Char32UUIDField(verbose_name='远程增强服务 ID'),
        ),
        migrations.AlterField(
            model_name='unboundremoteserviceengineappattachment',
            name='service_instance_id',
            field=paasng.utils.models.Char32UUIDField(null=True, verbose_name='远程增强服务实例 ID'),
        ),
    ]
