# Generated by Django 4.2.17 on 2025-03-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_privatetokenholder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprivatetoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="AuthenticatedAppAsUser",
        ),
        migrations.DeleteModel(
            name="UserPrivateToken",
        ),
    ]
