# Generated by Django 4.2.17 on 2025-03-11 11:49
"""Clean up system users which have been migrated to sysapi_client app."""
import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def forwards_func(apps, schema_editor):
    """Remove the system users that have been migrated to the sysapi_client app. Previously,
    the platform used the User/UserProfile to store the system client for calling system APIs.
    Now that these users have been migrated to sysapi_client.SysAPIClient, there is no longer
    a need to store them in the accounts app.
    """
    User = apps.get_model("accounts", "User")
    UserProfile = apps.get_model("accounts", "UserProfile")

    # See `ClientRole` to known more about these hardcoded role values
    sys_roles = {50, 60, 70, 80}
    for profile_id in UserProfile.objects.filter(role__in=sys_roles).values_list("id", flat=True):
        profile = UserProfile.objects.get(id=profile_id)

        # Delete the profile object
        logger.info("Deleting user %s", profile.user.username)
        profile.delete()

        # Delete the related User object
        try:
            User.objects.get(username=profile.user.username).delete()
        except User.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprivatetoken_user_and_more"),
    ]

    operations = [migrations.RunPython(forwards_func)]
