# Generated by Django 4.2.17 on 2025-03-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_clean_sys_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="enable_regions",
        ),
    ]
