# Generated by Django 4.2.16 on 2025-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_templates", "0002_appaddon_tenant_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appaddontemplate",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="appaddontemplate",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="模版名"),
        ),
        migrations.RemoveField(
            model_name="appaddontemplate",
            name="region",
        ),
    ]
