# Generated by Django 4.2.16 on 2025-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appmetricsmonitor",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
