# Generated by Django 3.2.12 on 2022-12-02 08:27

from django.db import migrations


def forward_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bk_plugins', '0004_auto_20220922_1919'),
        ('accounts', '0003_privatetokenholder')
    ]

    operations = [
        migrations.RunPython(code=forward_func)
    ]
