# Generated by Django 3.2.12 on 2023-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_plugins', '0006_bkplugintag_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bkplugintag',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='bkpluginprofile',
            name='pre_distributor_codes',
            field=models.JSONField(blank=True, null=True, verbose_name='预设的插件使用方的 code 列表'),
        ),
    ]
