version: '3.2'
services:
  bk_paas3_mysql:
    image: mysql:5.7.36
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${STORAGE_ROOT}/mysql:/var/lib/mysql/
      - ./provision/mysql/init:/docker-entrypoint-initdb.d
  bk_paas3_minio:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    command: server /data --console-address ":9000" --address ":9090"
    ports:
      - "9100:9000"
      - "9090:9090"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ${STORAGE_ROOT}/minio:/data
  bk_paas3_redis:
    image: redis:7.0.5
    command: 'redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'
    ports:
      - "6379:6379"
    volumes:
      - ${STORAGE_ROOT}/redis:/var/lib/redis
