apiVersion: v2
name: app-spark-api
description: App Spark API service
type: application
version: 0.1.0-alpha.1
appVersion: "0.1.0-alpha.1"
kubeVersion: ">=1.19.0-0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.13.3
