#!/usr/bin/env bash
# 在 bin/compile 命令一开始就注入，主要为了在所有命令执行之前进行初始化工作。
# shellcheck disable=SC2016

declare build

# 修复不正确的缩进
sed -i 's/echo -e "\${GREEN}       \$@\${NC}"/echo -e "\${GREEN}\$@\${NC}"/' "${buildpack}/lib/common.sh"
sed -i 's/echo -e "\${YELLOW} !!    \$@\${NC}"/echo -e "\${YELLOW}!! \$@\${NC}"/' "${buildpack}/lib/common.sh"
sed -i 's/echo -e >\&2 "\${RED} !!    \$@\${NC}"/echo -e >\&2 "\${RED}!! \$@\${NC}"/' "${buildpack}/lib/common.sh"

# 修复追踪模式下 git 命令污染日志的情况，且现阶段不支持 git 认证
sed -i '/setGitCredHelper() {/a \    return' "${buildpack}/lib/common.sh"
sed -i '/clearGitCredHelper() {/a \    return' "${buildpack}/lib/common.sh"

# 创建到 /tmp/build 的软链接，兼容 legacy-builder(PaaS V2)
if [ ! -e /tmp/build ]; then
    ln -sf "${build}" /tmp/build
fi