# Generated by Django 6.0.8 on 2026-08-19 09:22

import app_spark_api.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', app_spark_api.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='项目 ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('creator', app_spark_api.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('tenant_id', models.CharField(default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
            ],
            options={
                'unique_together': {('tenant_id', 'name')},
            },
        ),
    ]
