# Generated by Django 3.2.25 on 2024-06-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgrlegacy', '0004_wlappbackuprel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cnativemigrationprocess',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='cnativemigrationprocess',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('on_migration', 'On migration'), ('migration_succeeded', 'Migration succeeded'), ('migration_failed', 'Migration failed'), ('confirmed', 'Confirmed'), ('on_rollback', 'On rollback'), ('rollback_succeeded', 'Rollback succeeded'), ('rollback_failed', 'Rollback failed'), ('no_need_migration', 'No need migration')], default='default', max_length=20),
        ),
    ]
