# Generated by Django 4.2.16 on 2025-01-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mgrlegacy", "0005_auto_20240606_2254"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnativemigrationprocess",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="migrationprocess",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="wlappbackuprel",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
