# Generated by Django 5.2.15 on 2026-08-12 08:11

import paasng.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgrlegacy', '0006_cnativemigrationprocess_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlappbackuprel',
            name='backup_id',
            field=paasng.utils.models.Char32UUIDField(verbose_name='对应备份的 WlApp uuid'),
        ),
        migrations.AlterField(
            model_name='wlappbackuprel',
            name='original_id',
            field=paasng.utils.models.Char32UUIDField(verbose_name='原 WlApp uuid'),
        ),
    ]
