# Generated by Django 3.2.12 on 2022-10-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否已删除'),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='id',
            field=models.CharField(help_text='插件id', max_length=32),
        ),
    ]
