# Generated by Django 3.2.12 on 2022-11-01 09:57

from django.db import migrations
import paasng.pluginscenter.models.instances


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0004_approvalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='itsm_detail',
            field=paasng.pluginscenter.models.instances.ItsmDetailField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pluginreleasestage',
            name='itsm_detail',
            field=paasng.pluginscenter.models.instances.ItsmDetailField(default=None, null=True),
        ),
    ]
