# Generated by Django 3.2.12 on 2022-11-16 09:44

from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0006_auto_20221115_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('operator', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('action', models.CharField(choices=[('create', '创建'), ('add', '新建'), ('terminate', '终止发布'), ('modify', '修改'), ('delete', '删除')], max_length=32)),
                ('specific', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(choices=[('plugin', '插件'), ('version', '版本'), ('basic_info', '基本信息'), ('market_info', '市场信息'), ('config_info', '配置信息'), ('visible_range', '可见范围')], max_length=32)),
                ('plugin', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='pluginscenter.plugininstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
