# Generated by Django 3.2.12 on 2022-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0007_operationrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pluginconfiginfodefinition',
            old_name='title',
            new_name='title_zh_cn',
        ),
        migrations.AddField(
            model_name='pluginconfiginfodefinition',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='pluginconfiginfodefinition',
            name='description_zh_cn',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='pluginconfiginfodefinition',
            name='docs',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pluginconfiginfodefinition',
            name='title_en',
            field=models.CharField(blank=True, max_length=16, verbose_name='「配置管理标题」'),
        ),
    ]
