# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except
in compliance with the License. You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing permissions and
limitations under the License.

We undertake not to change the open source license (MIT license) applicable
to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.12 on 2022-12-05 07:14

from django.db import migrations, models
import paasng.pluginscenter.constants
import paasng.pluginscenter.models.definitions


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0008_auto_20221117_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugindefinition',
            name='features',
            field=paasng.pluginscenter.models.definitions.PluginFeaturesField(default=list),
        ),
        migrations.AddField(
            model_name='pluginrelease',
            name='retryable',
            field=models.BooleanField(default=True, help_text='失败后是否可重试'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('add', '新建'), ('re-release', '重新发布'), ('terminate', '终止发布'), ('modify', '修改'), ('delete', '删除'), ('archive', '下架')], max_length=32),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='status',
            field=models.CharField(choices=[('waiting-approval', '创建审批中'), ('approval-failed', '创建审批失败'), ('developing', '开发中'), ('releasing', '发布中'), ('released', '已发布'), ('archived', '已下架')], default=paasng.pluginscenter.constants.PluginStatus['WAITING_APPROVAL'], max_length=16, verbose_name='插件状态'),
        ),
    ]
