# Generated by Django 3.2.12 on 2023-01-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0009_auto_20221205_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrelease',
            name='complete_time',
            field=models.DateTimeField(default=None, help_text='发布完成时间, 执行完最后一个发布阶段后赋值'),
        ),
    ]
