# Generated by Django 3.2.12 on 2023-09-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluginscenter', '0011_auto_20230209_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginreleasestage',
            name='pipeline_detail',
            field=models.JSONField(default=None, help_text='该字段仅 invoke_method = pipeline 时可用', null=True, verbose_name='流水线构建详情'),
        ),
    ]
