# Generated by Django 3.2.12 on 2022-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20220507_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_scene_app',
            field=models.BooleanField(default=False, verbose_name='是否为场景 SaaS 应用'),
        ),
    ]
