# Generated by Django 3.2.12 on 2023-12-14 03:29

from django.db import migrations, models
from paasng.platform.applications.constants import ApplicationType
        
def forwards(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    Application.objects.filter(type="bk_plugin").update(
        is_plugin_app=True,
        type=ApplicationType.DEFAULT.value
    )

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_is_scene_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_plugin_app',
            field=models.BooleanField(default=False, help_text='蓝鲸应用插件：供标准运维、ITSM 等 SaaS 使用，有特殊逻辑', verbose_name='是否为插件应用'),
        ),
        migrations.RunPython(forwards),
    ]
