# Generated by Django 3.2.12 on 2024-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_is_plugin_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(db_index=True, default='default', help_text='与应用部署方式相关的类型信息', max_length=16, verbose_name='应用类型'),
        ),
    ]
