# Generated by Django 3.2.12 on 2024-04-18 02:21

from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('helper_text_zh_cn', models.CharField(help_text='形如：联系 xx 助手', max_length=64, verbose_name='助手展示信息')),
                ('helper_text_en', models.CharField(blank=True, help_text='形如：联系 xx 助手', max_length=64, verbose_name='助手展示信息')),
                ('helper_link', models.TextField(blank=True, help_text='形如：wxwork://message?uin=12345', verbose_name='助手的链接信息')),
                ('application', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='app_config', to='applications.application', verbose_name='蓝鲸应用')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
