# Generated by Django 3.2.25 on 2024-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_ai_agent_app',
            field=models.BooleanField(default=False, verbose_name='是否为 AI Agent 插件应用'),
        ),
    ]
