# Generated by Django 4.2.16 on 2024-11-06 03:11

from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_auto_20240904_1439'),
        ('applications', '0012_application_is_ai_agent_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDeploymentModuleOrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True, verbose_name='操作人')),
                ('before_order', models.JSONField(default=dict, verbose_name='排序前顺序')),
                ('after_order', models.JSONField(default=dict, verbose_name='排序后顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applications.application', verbose_name='应用')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDeploymentModuleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=20, verbose_name='模块名称')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='应用')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module', verbose_name='模块')),
            ],
            options={
                'verbose_name': '模块顺序',
                'unique_together': {('app', 'module')},
            },
        ),
    ]
