# Generated by Django 4.2.16 on 2024-11-28 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_auto_20240904_1439'),
        ('applications', '0013_applicationdeploymentmoduleorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdeploymentmoduleorder',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modules.module', verbose_name='模块'),
        ),
    ]
