# Generated by Django 4.2.16 on 2024-12-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_application_app_tenant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(max_length=20, verbose_name="应用名称"),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("name", "app_tenant_id")},
        ),
        migrations.CreateModel(
            name="SMartApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_code",
                    models.CharField(
                        max_length=20, verbose_name="描述文件中的应用原始 code"
                    ),
                ),
                (
                    "app",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.application",
                    ),
                ),
            ],
        ),
    ]
