# Generated by Django 4.2.17 on 2025-01-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_migrate_smart_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdeploymentmoduleorder",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="applicationenvironment",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="applicationfeatureflag",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="smartappextrainfo",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="usermarkedapplication",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
