# Generated by Django 4.2.16 on 2025-03-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_applicationdeploymentmoduleorder_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_scene_app',
        ),
    ]
