# Generated by Django 4.2.17 on 2025-04-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_remove_application_is_scene_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartappextrainfo",
            name="artifact_metadata",
            field=models.JSONField(
                default={},
                help_text="构件元信息, 包含 use_cnb 和 proc_entrypoints 信息",
            ),
        ),
    ]
