# Generated by Django 4.2.17 on 2025-04-24 03:27

from django.db import migrations
import paasng.platform.applications.entities
import paasng.platform.applications.models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_remove_application_is_scene_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartappextrainfo",
            name="artifact_metadata",
            field=paasng.platform.applications.models.SMartAppArtifactMetadataField(
                default=paasng.platform.applications.entities.SMartAppArtifactMetadata,
                help_text="smart app 的制品元数据",
            ),
        ),
    ]
