# Generated by Django 4.2.17 on 2025-06-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_smartappextrainfo_artifact_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability_level',
            field=models.CharField(default='not_set', max_length=32, verbose_name='可用性保障等级'),
        ),
    ]
