# Generated by Django 4.2.23 on 2026-04-08 07:05

from django.db import migrations, models
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_smartappextrainfo_artifact_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCodeAuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_code', models.CharField(help_text='8 位随机授权码', max_length=8, verbose_name='授权码')),
                ('app_code', models.CharField(help_text='必须以保留前缀开头的 app_code', max_length=20, unique=True, verbose_name='应用 Code')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
