# Generated by Django 4.2.30 on 2026-06-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_reservedprefixauthcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_isolated',
            field=models.BooleanField(default=False, help_text='应用需部署到网络/容器隔离环境（如 gvisor 集群）', verbose_name='是否隔离部署'),
        ),
    ]
