# Generated by Django 4.2.30 on 2026-06-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_reservedprefixauthcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_ai_agent_sandbox_app',
            field=models.BooleanField(default=False, help_text='需要长期运行且安全隔离的沙箱类插件应用', verbose_name='是否为 AI Agent 沙箱插件应用'),
        ),
    ]
