# Generated by Django 4.2.30 on 2026-07-08 17:12

import blue_krill.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_is_isolated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRuntimeEncryptionKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('stag', '预发布环境'), ('prod', '生产环境')], max_length=16, verbose_name='环境')),
                ('key', blue_krill.models.fields.EncryptField(verbose_name='运行时密钥')),
                ('cipher_type', models.CharField(default='FernetCipher', max_length=16, verbose_name='加密算法类型')),
                ('tenant_id', models.CharField(db_index=True, default='default', help_text='本条数据的所属租户', max_length=32, verbose_name='租户 ID')),
                ('application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='runtime_encryption_keys', to='applications.application')),
            ],
            options={
                'unique_together': {('application', 'environment')},
            },
        ),
    ]
