# Generated by Django 4.2.30 on 2026-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_is_isolated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_isolated',
        ),
        migrations.AddField(
            model_name='application',
            name='deploy_policy',
            field=models.CharField(default='default', help_text='应用部署策略（隔离性/安全性维度），如 isolated 表示需部署到网络/容器隔离环境（如 gvisor 集群）', max_length=32, verbose_name='部署策略'),
        ),
    ]
