# Generated by Django 3.2.12 on 2024-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppResourceUsageReport',
            fields=[
                ('app_code', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='应用 Code')),
                ('app_name', models.CharField(max_length=128, verbose_name='应用名称')),
                ('cpu_requests', models.IntegerField(default=0, verbose_name='CPU 请求')),
                ('mem_requests', models.IntegerField(default=0, verbose_name='内存请求')),
                ('cpu_limits', models.IntegerField(default=0, verbose_name='CPU 限制')),
                ('mem_limits', models.IntegerField(default=0, verbose_name='内存限制')),
                ('cpu_usage_avg', models.FloatField(default=0, verbose_name='CPU 平均使用率')),
                ('mem_usage_avg', models.FloatField(default=0, verbose_name='内存平均使用率')),
                ('pv', models.BigIntegerField(default=0, verbose_name='近一周页面访问量')),
                ('uv', models.BigIntegerField(default=0, verbose_name='近一周访问用户数')),
                ('summary', models.JSONField(default=dict, verbose_name='资源使用详情汇总')),
                ('operator', models.CharField(max_length=128, null=True, verbose_name='最后操作人')),
                ('collected_at', models.DateTimeField(verbose_name='数据统计时间')),
            ],
        ),
    ]
