# Generated by Django 2.2.17 on 2021-10-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_appsubpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdomain',
            name='path_prefix',
            field=models.CharField(default='/', help_text='the accessable path for current domain', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='appdomain',
            unique_together={('region', 'host', 'path_prefix')},
        ),
    ]
