# Generated by Django 3.2.12 on 2022-12-12 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0004_auto_20220331_1058'),
    ]
    replaces = [
        ("services", "0005_auto_20221212_1810"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='lb_plan',
        ),
        migrations.AlterField(
            model_name='appdomaincert',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')]),
        ),
        migrations.AlterField(
            model_name='appdomainsharedcert',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')]),
        ),
    ]
