# Generated by Django 3.2.12 on 2022-09-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SceneTmpl',
        ),
    ]
