# Generated by Django 4.2.17 on 2025-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_applatestoperationrecord_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoperationrecord',
            name='attribute',
            field=models.CharField(blank=True, help_text='如增强服务的属性可以为：mysql、bkrepo', max_length=128, null=True, verbose_name='对象属性'),
        ),
        migrations.AlterField(
            model_name='adminoperationrecord',
            name='operation',
            field=models.CharField(max_length=32, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='adminoperationrecord',
            name='target',
            field=models.CharField(max_length=32, verbose_name='操作对象'),
        ),
        migrations.AlterField(
            model_name='appoperationrecord',
            name='attribute',
            field=models.CharField(blank=True, help_text='如增强服务的属性可以为：mysql、bkrepo', max_length=128, null=True, verbose_name='对象属性'),
        ),
        migrations.AlterField(
            model_name='appoperationrecord',
            name='operation',
            field=models.CharField(max_length=32, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='appoperationrecord',
            name='target',
            field=models.CharField(max_length=32, verbose_name='操作对象'),
        ),
    ]
