apiVersion: paas.bk.tencent.com/v1alpha1
kind: BkApp
metadata:
  name: sample-app-v1a1
spec:
  processes:
    - name: web
      replicas: 1
      image: nginx:latest
      cpu: 500m
      memory: 256Mi
    - name: static
      replicas: 1
      image: busybox:latest
      command:
        - /bin/sh
      args:
        - "-c"
        - "echo hello; sleep 3600"
  hooks:
    preRelease:
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "echo hello; sleep 1;"
  configuration:
    env:
      - name: ENV_VAR_KEY
        value: env_var_value
  envOverlay:
    replicas:
      - envName: stag
        process: web
        count: 2
    envVariables:
      - envName: prod
        name: ENV_ONLY_FOR_STAG
        value: foo