# Generated by Django 2.2.17 on 2020-12-10 10:08

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionClusterState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(max_length=32)),
                ('cluster_name', models.CharField(max_length=32, null=True)),
                ('name', models.CharField(max_length=64, verbose_name='informative name of state')),
                ('nodes_digest', models.CharField(db_index=True, max_length=64)),
                ('nodes_cnt', models.IntegerField(default=0)),
                ('nodes_name', jsonfield.fields.JSONField(blank=True, default=[])),
                ('nodes_data', jsonfield.fields.JSONField(blank=True, default=[])),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'unique_together': {('region', 'cluster_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RCStateAppBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.App')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='region.RegionClusterState')),
            ],
            options={
                'unique_together': {('app', 'state')},
            },
        ),
    ]
