# Generated by Django 3.2.12 on 2023-09-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230717_1958'),
        ('processes', '0003_auto_20230328_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='WlAppProbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(max_length=255)),
                ('probe_type', models.CharField(choices=[('readiness', 'readinessProbe'), ('liveness', 'livenessProbe'), ('startup', 'startupProbe')], max_length=255)),
                ('check_mechanism', models.JSONField(default=None)),
                ('initial_delay_seconds', models.IntegerField(default=0)),
                ('timeout_seconds', models.PositiveIntegerField(default=1)),
                ('period_seconds', models.PositiveIntegerField(default=10)),
                ('success_threshold', models.PositiveIntegerField(default=1)),
                ('failure_threshold', models.PositiveIntegerField(default=3)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wlapp_probes', to='api.app')),
            ],
        ),
    ]
