# Generated by Django 4.2.30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agent_sandbox", "0009_add_build_type_to_imagebuildrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="SidecarImage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("app_code", models.CharField(help_text="发起方应用 code（sysapi client）", max_length=20)),
                (
                    "image",
                    models.CharField(help_text="完整镜像地址（registry/namespace/name:tag）", max_length=512),
                ),
                ("name", models.CharField(help_text="镜像名称（用于展示/筛选）", max_length=256)),
                ("tag", models.CharField(help_text="镜像标签", max_length=128)),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
                (
                    "build_record",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="关联的构建记录（直接注册时为空）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sidecar_images",
                        to="agent_sandbox.imagebuildrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("tenant_id", "app_code", "image")},
            },
        ),
    ]
