# Generated by Django 4.2.17 on 2025-01-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ci", "0002_auto_20230807_1727"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciatomjob",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="ciresourceappenvrelation",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="ciresourceatom",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
