# Generated by Django 6.0.8 on 2026-09-24 03:08

import blue_krill.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="E2BSandboxRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sandbox_id", models.CharField(max_length=128, null=True, unique=True, verbose_name="E2B 沙箱 ID")),
                ("project_id", models.CharField(db_index=True, max_length=128, verbose_name="原始项目 ID")),
                ("conversation_id", models.CharField(db_index=True, max_length=128, verbose_name="原始会话 ID")),
                (
                    "active_project_id",
                    models.CharField(max_length=128, null=True, unique=True, verbose_name="占用中的项目 ID"),
                ),
                (
                    "active_conversation_id",
                    models.CharField(max_length=128, null=True, unique=True, verbose_name="占用中的会话 ID"),
                ),
                ("runtime_token", blue_krill.models.fields.EncryptField(verbose_name="Agent Runtime 访问令牌")),
                ("template", models.CharField(max_length=128, verbose_name="沙箱模板")),
                ("sandbox_domain", models.CharField(max_length=255, null=True, verbose_name="沙箱访问域名")),
                ("envd_version", models.CharField(max_length=64, null=True, verbose_name="沙箱 envd 版本")),
                ("sandbox_headers", blue_krill.models.fields.EncryptField(default="{}", verbose_name="沙箱连接头")),
                (
                    "traffic_access_token",
                    blue_krill.models.fields.EncryptField(null=True, verbose_name="端口代理访问令牌"),
                ),
                ("stopped_at", models.DateTimeField(default=None, null=True, verbose_name="停止或失效时间")),
                ("stop_reason", models.CharField(blank=True, default="", max_length=32, verbose_name="停止原因")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["conversation_id", "-created_at"], name="runtime_e2b_convers_e3da71_idx")
                ],
            },
        ),
    ]
