# Generated by Django 6.0.8 on 2026-09-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2bsandboxrecord',
            name='agent_pid',
            field=models.PositiveIntegerField(null=True, verbose_name='Agent 进程 ID'),
        ),
    ]
