# Generated by Django 4.2.23 on 2025-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sourcectl",
            "0012_dockerrepository_tenant_id_gitrepository_tenant_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcepackage",
            name="pkg_sha256_signature",
            field=models.CharField(
                max_length=64, null=True, verbose_name="原始包的 sha256 数字签名"
            ),
        ),
        migrations.AlterField(
            model_name="sourcepackage",
            name="sha256_signature",
            field=models.CharField(
                help_text="镜像方案时, 该字段记录镜像配置文件的 sha256; 原始包方案时, 该字段记录原始包的 sha256",
                max_length=64,
                null=True,
                verbose_name="sha256 数字签名",
            ),
        ),
    ]
