version: '3.2'
services:
  mysql_main:
    container_name: "paasng_mysql_main"
    image: mysql:5.7.22
    volumes:
      - ${STORAGE_ROOT}/mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: bk_paas_ng
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
      ]
  minio:
    container_name: "paasng_minio"
    image: minio/minio:RELEASE.2018-08-02T23-11-36Z
    command: server /data
    volumes:
      - ${STORAGE_ROOT}/minio:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  redis_main:
    container_name: "paasng_redis_main"
    image: redis:3.2.0
    volumes:
      - ${STORAGE_ROOT}/redis:/var/lib/redis
  svn-server:
    container_name: "paasng_svn_server"
    image: "garethflowers/svn-server"
    volumes:
      - ${STORAGE_ROOT}/svn-server:/var/opt/svn

networks:
  default:
    external:
      name: ${NETWORK_NAME}
