# Generated by Django 4.2.17 on 2025-03-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0005_template_runtime_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="is_hidden",
            field=models.BooleanField(
                default=False, help_text="被隐藏的模板不会出现在创建应用时的列表中", verbose_name="是否隐藏"
            ),
        ),
    ]
