# Generated by Django 3.2.25 on 2024-10-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_template_runtime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDashBoardTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='仪表盘名称，如：bksaas/framework-python', max_length=64, unique=True)),
                ('display_name', models.CharField(help_text='仪表盘展示名称，如：Python 开发框架内置仪表盘', max_length=512)),
                ('version', models.CharField(max_length=32)),
                ('language', models.CharField(max_length=32, verbose_name='仪表盘所属语言')),
                ('is_plugin_template', models.BooleanField(default=False, verbose_name='是否为插件应用的模板')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
