# Generated by Django 4.2.17 on 2025-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0007_set_is_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="enabled_regions",
        ),
        migrations.AlterField(
            model_name="template",
            name="blob_url",
            field=models.JSONField(verbose_name="二进制包存储路径"),
        ),
    ]
