# Generated by Django 4.2.17 on 2025-05-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0009_update_blob_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="render_method",
            field=models.CharField(
                default="django_template", max_length=32, verbose_name="模板渲染方式"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="source_dir",
            field=models.CharField(
                blank=True, default="./", max_length=256, verbose_name="模板代码所在目录"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="repo_url",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="代码仓库地址"
            ),
        ),
    ]
