# Generated by Django 4.2.17 on 2025-06-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0010_template_render_method_template_source_dir_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="repo_type",
            field=models.CharField(
                default="",
                help_text="将模板从代码仓库下载到本地时需要使用到",
                max_length=32,
                verbose_name="代码仓库类型",
            ),
        ),
    ]
