# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
# Copyright (C) Tencent. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.

# Generated by Django 4.2.30 on 2026-06-08 07:06

from django.db import migrations, models


def populate_supported_runtime_types(apps, schema_editor):
    """将现有模板的 supported_runtime_types 填充为 [runtime_type]"""

    Template = apps.get_model("templates", "Template")
    for tmpl in Template.objects.all():
        if tmpl.runtime_type and not tmpl.supported_runtime_types:
            tmpl.supported_runtime_types = [tmpl.runtime_type]
            tmpl.save(update_fields=["supported_runtime_types"])


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_template_repo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='supported_runtime_types',
            field=models.JSONField(blank=True, default=list, verbose_name='支持的运行时类型'),
        ),
        migrations.RunPython(
            populate_supported_runtime_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
