# Generated by Django 4.2.17 on 2025-07-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_template_repo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('normal', '普通应用'), ('plugin', '插件应用')], max_length=16, verbose_name='模板类型'),
        ),
    ]
