# Generated by Django 5.2.15 on 2026-08-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0012_template_supported_runtime_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('normal', '普通应用'), ('plugin', '插件应用')], max_length=16, verbose_name='模板类型'),
        ),
    ]
