# -------------- unittest container --------------
# Build the manager binary
FROM golang:1.18 as builder

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/
COPY pkg/ pkg/
COPY hack/ hack/
COPY Makefile Makefile

# Install dependent tools
RUN make controller-gen envtest ginkgo golines gofumpt golangci-lint

RUN apt-get update && apt-get install -y vim
