# -------------- unittest container --------------
FROM golang:1.25.10-alpine3.23

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY config/ config/
COPY controllers/ controllers/
COPY pkg/ pkg/
COPY hack/ hack/
COPY Makefile Makefile

# Install dependent tools
RUN apk --update --no-cache add bash make vim curl tar
RUN make controller-gen envtest ginkgo golines gofumpt golangci-lint

# Preinstall envtest assets because the GCS kubebuilder-tools bucket used by
# this setup-envtest version is no longer available.
ARG ETCD_VERSION=v3.5.4
RUN set -eux; \
    ENVTEST_DIR="/root/.local/share/kubebuilder-envtest/k8s/1.24.1-linux-amd64"; \
    mkdir -p "${ENVTEST_DIR}"; \
    cd "${ENVTEST_DIR}"; \
    curl -fsSL -o kube-apiserver "https://dl.k8s.io/v1.24.1/bin/linux/amd64/kube-apiserver"; \
    curl -fsSL -o kubectl "https://dl.k8s.io/v1.24.1/bin/linux/amd64/kubectl"; \
    curl -fsSL -o etcd.tar.gz \
        "https://github.com/etcd-io/etcd/releases/download/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-amd64.tar.gz"; \
    tar xzf etcd.tar.gz; \
    mv "etcd-${ETCD_VERSION}-linux-amd64/etcd" ./etcd; \
    rm -rf etcd.tar.gz "etcd-${ETCD_VERSION}-linux-amd64"; \
    chmod +x kube-apiserver kubectl etcd
