# -*- coding: utf-8 -*-
# TencentBlueKing is pleased to support the open source community by making
# 蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# We undertake not to change the open source license (MIT license) applicable
# to the current version of the project delivered to anyone in the future.

# Generated by Django 2.2.17 on 2021-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20210110_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='build_int_requested_at',
            field=models.DateTimeField(help_text='用户请求中断 build 的时间', null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='release_int_requested_at',
            field=models.DateTimeField(help_text='用户请求中断 release 的时间', null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='build_status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('interrupted', 'Interrupted')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='release_status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('interrupted', 'Interrupted')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('interrupted', 'Interrupted')], default='pending', max_length=16, verbose_name='部署状态'),
        ),
        migrations.AlterField(
            model_name='deployphase',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('interrupted', 'Interrupted')], max_length=32, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='deploystep',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('interrupted', 'Interrupted')], max_length=32, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='moduleenvironmentoperations',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('interrupted', 'Interrupted')], default='pending', max_length=16, verbose_name='操作状态'),
        ),
        migrations.AlterField(
            model_name='offlineoperation',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('interrupted', 'Interrupted')], default='pending', max_length=16, verbose_name='下线状态'),
        ),
        migrations.AlterField(
            model_name='oneoffcommand',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending'), ('interrupted', 'Interrupted')], default='pending', max_length=16),
        ),
    ]
