# Generated by Django 3.2.12 on 2023-08-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_deployment_bkapp_revision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='bkapp_revision_id',
            field=models.IntegerField(help_text='本次发布指定的 BkApp Revision id', null=True),
        ),
    ]
