# Generated by Django 3.2.12 on 2023-08-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_alter_deployment_bkapp_revision_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='bkapp_release_id',
            field=models.BigIntegerField(help_text='云原生应用发布记录ID', null=True),
        ),
    ]
