# Generated by Django 3.2.12 on 2023-12-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_reset_step_meta_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='main_stream_id',
            field=models.UUIDField(help_text='the logs at the main phase', null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='preparation_stream_id',
            field=models.UUIDField(help_text='the logs at the preparation phase', null=True),
        ),
    ]
