# Generated by Django 3.2.12 on 2023-12-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_auto_20231019_0944'),
        ('engine', '0018_auto_20231207_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploystepmeta',
            name='builder_provider',
        ),
        migrations.RemoveField(
            model_name='deploystepmeta',
            name='buildpack_provider',
        ),
        migrations.AddField(
            model_name='stepmetaset',
            name='builder_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_meta_sets', to='modules.appslugbuilder', verbose_name='由 SlugBuild 提供'),
        ),
    ]
