# Generated by Django 3.2.12 on 2023-12-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_auto_20231207_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneOffCommand',
        ),
    ]
