# Generated by Django 3.2.12 on 2023-12-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_delete_oneoffcommand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploystepmeta',
            name='builder_provider',
        ),
        migrations.RemoveField(
            model_name='deploystepmeta',
            name='buildpack_provider',
        ),
    ]
