# Generated by Django 3.2.25 on 2024-07-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_presetenvvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultConfigVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='环境变量名')),
                ('value', models.TextField(verbose_name='环境变量值')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='描述')),
                ('updater', models.CharField(max_length=128, null=True, verbose_name='更新者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'unique_together': {('key',)},
            },
        ),
    ]
