# Generated by Django 4.2.16 on 2024-11-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0022_builtinconfigvar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deployment",
            name="hooks",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="procfile",
        ),
    ]
