# Generated by Django 4.2.17 on 2025-04-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_buildconfig_tenant_id'),
        ('engine', '0024_configvar_tenant_id_deployment_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presetenvvariable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presetenvvariable',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='presetenvvariable',
            unique_together={('module', 'environment_name', 'key', 'description')},
        ),
    ]
