# Generated by Django 4.2.17 on 2025-07-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_presetenvvariable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvar',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
