# Generated by Django 4.2.23 on 2025-07-21 07:46

import blue_krill.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_presetenvvariable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvar',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='value 值是否敏感'),
        ),
        migrations.AlterField(
            model_name='configvar',
            name='value',
            field=blue_krill.models.fields.EncryptField(null=False),
        ),
    ]
