# Generated by Django 4.2.23 on 2025-08-12 07:04

from django.db import migrations, models
import django.db.models.deletion
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0019_smartappextrainfo_artifact_metadata"),
        ("engine", "0027_manually_encrypt_config_var_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configvar",
            name="value",
            field=paasng.utils.models.RobustEncryptField(),
        ),
        migrations.AlterField(
            model_name="moduleenvironmentoperations",
            name="operation_type",
            field=models.CharField(
                choices=[("offline", "下架"), ("online", "部署")], max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="presetenvvariable",
            name="value",
            field=paasng.utils.models.RobustEncryptField(),
        ),
        migrations.CreateModel(
            name="DeployOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(help_text="部署区域", max_length=32)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "replicas_override_policy",
                    models.CharField(
                        help_text="副本数的覆盖策略", max_length=20, null=True
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deploy_options",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
