# Generated by Django 4.2.23 on 2025-08-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0019_smartappextrainfo_artifact_metadata"),
        ("engine", "0027_manually_encrypt_config_var_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleenvironmentoperations",
            name="operation_type",
            field=models.CharField(
                choices=[("offline", "下架"), ("online", "部署")], max_length=32
            ),
        ),
        migrations.CreateModel(
            name="DeployOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "replicas_policy",
                    models.CharField(
                        help_text="副本数的优先策略", max_length=20, null=True
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="本条数据的所属租户",
                        max_length=32,
                        verbose_name="租户 ID",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deploy_options",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
