# Generated by Django 4.2.23 on 2025-09-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0028_alter_moduleenvironmentoperations_operation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleenvironmentoperations",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
