# Generated by Django 5.2.15 on 2026-08-12 08:11

import paasng.utils.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0030_add_sys_prefix_to_builtinconfigvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='build_id',
            field=paasng.utils.models.Char32UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='build_process_id',
            field=paasng.utils.models.Char32UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='id',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='main_stream_id',
            field=paasng.utils.models.Char32UUIDField(help_text='the logs at the main phase', null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='pre_release_id',
            field=paasng.utils.models.Char32UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='preparation_stream_id',
            field=paasng.utils.models.Char32UUIDField(help_text='the logs at the preparation phase', null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='release_id',
            field=paasng.utils.models.Char32UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='deployphase',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='deploystep',
            name='uuid',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='engineapp',
            name='id',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='moduleenvironmentoperations',
            name='id',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='moduleenvironmentoperations',
            name='object_uid',
            field=paasng.utils.models.Char32UUIDField(default=uuid.uuid4, editable=False, verbose_name='详情记录的UUID'),
        ),
        migrations.AlterField(
            model_name='offlineoperation',
            name='id',
            field=paasng.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
