# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making
蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
Copyright (C) 2017-2022THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.

We undertake not to change the open source license (MIT license) applicable

to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 2.2.17 on 2021-12-07 09:26

from django.db import migrations, models
import paasng.dev_resources.sourcectl.models
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcectl', '0003_auto_20211014_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='部署区域', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', paasng.utils.models.BkUserField(blank=True, db_index=True, max_length=64, null=True)),
                ('server_name', models.CharField(max_length=32, verbose_name='DockerRegistry 服务名称')),
                ('repo_url', models.CharField(max_length=2048, verbose_name='项目地址')),
                ('source_dir', models.CharField(max_length=2048, null=True, verbose_name='源码目录')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, paasng.dev_resources.sourcectl.models.RepositoryMixin),
        ),
    ]
