# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸智云 - PaaS 平台 (BlueKing - PaaS System) available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except
in compliance with the License. You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing permissions and
limitations under the License.

We undertake not to change the open source license (MIT license) applicable
to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.12 on 2022-09-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcectl', '0005_alter_dockerrepository_repo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTypeSpecConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='服务名称')),
                ('label_zh_cn', models.CharField(max_length=32, verbose_name='标签')),
                ('label_en', models.CharField(blank=True, max_length=32, verbose_name='标签')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('spec_cls', models.CharField(max_length=128, verbose_name='配置类路径')),
                ('server_config', models.JSONField(blank=True, default=dict, max_length=512, verbose_name='服务配置')),
                ('display_info_zh_cn', models.JSONField(blank=True, default=dict, max_length=512, verbose_name='展示信息')),
                ('display_info_en', models.JSONField(blank=True, default=dict, max_length=512, verbose_name='展示信息')),
                ('authorization_base_url', models.CharField(blank=True, default='', max_length=256, verbose_name='OAuth 授权链接')),
                ('client_id', models.CharField(blank=True, default='', max_length=256, verbose_name='OAuth App Client ID')),
                ('client_secret', models.CharField(blank=True, default='', max_length=256, verbose_name='OAuth App Client Secret')),
                ('redirect_uri', models.CharField(blank=True, default='', max_length=256, verbose_name='重定向（回调）地址')),
                ('token_base_url', models.CharField(blank=True, default='', max_length=256, verbose_name='获取 Token 链接')),
                ('oauth_display_info_zh_cn', models.JSONField(blank=True, default=dict, max_length=512, verbose_name='OAuth 展示信息')),
                ('oauth_display_info_en', models.JSONField(blank=True, default=dict, max_length=512, verbose_name='OAuth 展示信息')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
