# Generated by Django 3.2.12 on 2022-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcectl', '0007_init_source_type_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetypespecconfig',
            name='display_info_en',
            field=models.JSONField(blank=True, default=dict, verbose_name='展示信息'),
        ),
        migrations.AlterField(
            model_name='sourcetypespecconfig',
            name='display_info_zh_cn',
            field=models.JSONField(blank=True, default=dict, verbose_name='展示信息'),
        ),
        migrations.AlterField(
            model_name='sourcetypespecconfig',
            name='oauth_display_info_en',
            field=models.JSONField(blank=True, default=dict, verbose_name='OAuth 展示信息'),
        ),
        migrations.AlterField(
            model_name='sourcetypespecconfig',
            name='oauth_display_info_zh_cn',
            field=models.JSONField(blank=True, default=dict, verbose_name='OAuth 展示信息'),
        ),
        migrations.AlterField(
            model_name='sourcetypespecconfig',
            name='server_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='服务配置'),
        ),
    ]
