#!/usr/bin/with-contenv bash

if [ "$ENABLE_CODE_EDITOR" = "true" ]; then
  echo "starting code-server"
  # PORT="" 用于忽略容器提供的 PORT 环境变量（5000）
  # --bind-addr 0.0.0.0:8080 使服务能通过 8080 端口对容器外提供服务
  # --disable-telemetry 禁止遥测数据收集功能
  # --disable-update-check 关闭 code-server 自动更新
  # 参考文档：
  # https://code.visualstudio.com/docs/configure/telemetry
  # https://code.visualstudio.com/docs/supporting/FAQ#_telemetry-and-crash-reporting
  # https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates
  PORT="" /usr/bin/code-server --bind-addr 0.0.0.0:8080 --disable-telemetry --disable-update-check
else
  echo "code-server is not enabled, skip..."
fi
