# Generated by Django 4.2.16 on 2025-01-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_auto_20230313_1751"),
    ]

    operations = [
        migrations.AddField(
            model_name="appimagecredential",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
        migrations.AddField(
            model_name="appusercredential",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="本条数据的所属租户",
                max_length=32,
                verbose_name="租户 ID",
            ),
        ),
    ]
