# Generated by Django 5.2.15 on 2026-08-12 08:11

import paas_wl.utils.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_appimagecredential_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appimagecredential',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='appusercredential',
            name='application_id',
            field=paas_wl.utils.models.Char32UUIDField(verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='appusercredential',
            name='uuid',
            field=paas_wl.utils.models.Char32UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
