# Generated by Django 2.2.17 on 2021-08-04 10:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210508_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='env_variables',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
