# Generated by Django 2.2.17 on 2021-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210804_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='artifact_deleted',
            field=models.BooleanField(default=False, help_text='slug是否已被清理'),
        ),
        migrations.AlterField(
            model_name='build',
            name='slug_path',
            field=models.TextField(help_text='slug path 形如 {region}/home/{name}:{branch}:{revision}/push'),
        ),
        migrations.AlterField(
            model_name='buildprocess',
            name='status',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('successful', 'SUCCESSFUL'), ('failed', 'FAILED'), ('pending', 'PENDING'), ('interrupted', 'INTERRUPTED')], default='pending', max_length=12),
        ),
    ]
