# Generated by Django 2.2.17 on 2021-12-14 02:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211022_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildprocess',
            name='status',
            field=models.CharField(choices=[('successful', 'SUCCESSFUL'), ('failed', 'FAILED'), ('pending', 'PENDING'), ('interrupted', 'INTERRUPTED')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='config',
            name='tolerations',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
