# Generated by Django 2.2.17 on 2021-12-15 08:53

import paas_wl.utils.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211214_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='procfile',
            field=jsonfield.fields.JSONField(
                blank=True, default={}, validators=[paas_wl.utils.models.validate_procfile]
            ),
        ),
        migrations.AlterField(
            model_name='build',
            name='branch',
            field=models.CharField(help_text='readable version, such as trunk/master', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='revision',
            field=models.CharField(help_text='unique version, such as sha256', max_length=128, null=True),
        ),
    ]
