# Generated by Django 2.2.17 on 2021-12-15 10:27

import paas_wl.platform.applications.models.config
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211215_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='runtime',
            field=paas_wl.platform.applications.models.config.RuntimeConfigField(
                default=paas_wl.platform.applications.models.config.RuntimeConfig
            ),
        ),
    ]
