# Generated by Django 3.2.12 on 2022-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_config_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.CharField(db_index=True, default='default', max_length=16, verbose_name='应用类型'),
        ),
    ]
